/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetShopInfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetShopInfo200Response{}

// GetShopInfo200Response struct for GetShopInfo200Response
type GetShopInfo200Response struct {
	Header *ResponseHeader `json:"header,omitempty"`
	Data []GetShopInfo200ResponseDataInner `json:"data,omitempty"`
}

// NewGetShopInfo200Response instantiates a new GetShopInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetShopInfo200Response() *GetShopInfo200Response {
	this := GetShopInfo200Response{}
	return &this
}

// NewGetShopInfo200ResponseWithDefaults instantiates a new GetShopInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetShopInfo200ResponseWithDefaults() *GetShopInfo200Response {
	this := GetShopInfo200Response{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *GetShopInfo200Response) GetHeader() ResponseHeader {
	if o == nil || IsNil(o.Header) {
		var ret ResponseHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShopInfo200Response) GetHeaderOk() (*ResponseHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *GetShopInfo200Response) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given ResponseHeader and assigns it to the Header field.
func (o *GetShopInfo200Response) SetHeader(v ResponseHeader) {
	o.Header = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetShopInfo200Response) GetData() []GetShopInfo200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetShopInfo200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetShopInfo200Response) GetDataOk() ([]GetShopInfo200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetShopInfo200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetShopInfo200ResponseDataInner and assigns it to the Data field.
func (o *GetShopInfo200Response) SetData(v []GetShopInfo200ResponseDataInner) {
	o.Data = v
}

func (o GetShopInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetShopInfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetShopInfo200Response struct {
	value *GetShopInfo200Response
	isSet bool
}

func (v NullableGetShopInfo200Response) Get() *GetShopInfo200Response {
	return v.value
}

func (v *NullableGetShopInfo200Response) Set(val *GetShopInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetShopInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetShopInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetShopInfo200Response(val *GetShopInfo200Response) *NullableGetShopInfo200Response {
	return &NullableGetShopInfo200Response{value: val, isSet: true}
}

func (v NullableGetShopInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetShopInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


