/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetOrderCobCod200ResponseDataOrderDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderCobCod200ResponseDataOrderDataInner{}

// GetOrderCobCod200ResponseDataOrderDataInner struct for GetOrderCobCod200ResponseDataOrderDataInner
type GetOrderCobCod200ResponseDataOrderDataInner struct {
	Order *GetOrderCobCod200ResponseDataOrderDataInnerOrder `json:"order,omitempty"`
	OrderHistory []GetOrderCobCod200ResponseDataOrderDataInnerOrderHistoryInner `json:"order_history,omitempty"`
	OrderDetail []GetOrderCobCod200ResponseDataOrderDataInnerOrderDetailInner `json:"order_detail,omitempty"`
	DropShipper *GetOrderCobCod200ResponseDataOrderDataInnerDropShipper `json:"drop_shipper,omitempty"`
	TypeMeta *GetOrderCobCod200ResponseDataOrderDataInnerTypeMeta `json:"type_meta,omitempty"`
	OrderShipmentFulfillment *GetOrderCobCod200ResponseDataOrderDataInnerOrderShipmentFulfillment `json:"order_shipment_fulfillment,omitempty"`
	BookingData *GetOrderCobCod200ResponseDataOrderDataInnerBookingData `json:"booking_data,omitempty"`
}

// NewGetOrderCobCod200ResponseDataOrderDataInner instantiates a new GetOrderCobCod200ResponseDataOrderDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderCobCod200ResponseDataOrderDataInner() *GetOrderCobCod200ResponseDataOrderDataInner {
	this := GetOrderCobCod200ResponseDataOrderDataInner{}
	return &this
}

// NewGetOrderCobCod200ResponseDataOrderDataInnerWithDefaults instantiates a new GetOrderCobCod200ResponseDataOrderDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderCobCod200ResponseDataOrderDataInnerWithDefaults() *GetOrderCobCod200ResponseDataOrderDataInner {
	this := GetOrderCobCod200ResponseDataOrderDataInner{}
	return &this
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrder() GetOrderCobCod200ResponseDataOrderDataInnerOrder {
	if o == nil || IsNil(o.Order) {
		var ret GetOrderCobCod200ResponseDataOrderDataInnerOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderOk() (*GetOrderCobCod200ResponseDataOrderDataInnerOrder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given GetOrderCobCod200ResponseDataOrderDataInnerOrder and assigns it to the Order field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetOrder(v GetOrderCobCod200ResponseDataOrderDataInnerOrder) {
	o.Order = &v
}

// GetOrderHistory returns the OrderHistory field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderHistory() []GetOrderCobCod200ResponseDataOrderDataInnerOrderHistoryInner {
	if o == nil || IsNil(o.OrderHistory) {
		var ret []GetOrderCobCod200ResponseDataOrderDataInnerOrderHistoryInner
		return ret
	}
	return o.OrderHistory
}

// GetOrderHistoryOk returns a tuple with the OrderHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderHistoryOk() ([]GetOrderCobCod200ResponseDataOrderDataInnerOrderHistoryInner, bool) {
	if o == nil || IsNil(o.OrderHistory) {
		return nil, false
	}
	return o.OrderHistory, true
}

// HasOrderHistory returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasOrderHistory() bool {
	if o != nil && !IsNil(o.OrderHistory) {
		return true
	}

	return false
}

// SetOrderHistory gets a reference to the given []GetOrderCobCod200ResponseDataOrderDataInnerOrderHistoryInner and assigns it to the OrderHistory field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetOrderHistory(v []GetOrderCobCod200ResponseDataOrderDataInnerOrderHistoryInner) {
	o.OrderHistory = v
}

// GetOrderDetail returns the OrderDetail field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderDetail() []GetOrderCobCod200ResponseDataOrderDataInnerOrderDetailInner {
	if o == nil || IsNil(o.OrderDetail) {
		var ret []GetOrderCobCod200ResponseDataOrderDataInnerOrderDetailInner
		return ret
	}
	return o.OrderDetail
}

// GetOrderDetailOk returns a tuple with the OrderDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderDetailOk() ([]GetOrderCobCod200ResponseDataOrderDataInnerOrderDetailInner, bool) {
	if o == nil || IsNil(o.OrderDetail) {
		return nil, false
	}
	return o.OrderDetail, true
}

// HasOrderDetail returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasOrderDetail() bool {
	if o != nil && !IsNil(o.OrderDetail) {
		return true
	}

	return false
}

// SetOrderDetail gets a reference to the given []GetOrderCobCod200ResponseDataOrderDataInnerOrderDetailInner and assigns it to the OrderDetail field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetOrderDetail(v []GetOrderCobCod200ResponseDataOrderDataInnerOrderDetailInner) {
	o.OrderDetail = v
}

// GetDropShipper returns the DropShipper field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetDropShipper() GetOrderCobCod200ResponseDataOrderDataInnerDropShipper {
	if o == nil || IsNil(o.DropShipper) {
		var ret GetOrderCobCod200ResponseDataOrderDataInnerDropShipper
		return ret
	}
	return *o.DropShipper
}

// GetDropShipperOk returns a tuple with the DropShipper field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetDropShipperOk() (*GetOrderCobCod200ResponseDataOrderDataInnerDropShipper, bool) {
	if o == nil || IsNil(o.DropShipper) {
		return nil, false
	}
	return o.DropShipper, true
}

// HasDropShipper returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasDropShipper() bool {
	if o != nil && !IsNil(o.DropShipper) {
		return true
	}

	return false
}

// SetDropShipper gets a reference to the given GetOrderCobCod200ResponseDataOrderDataInnerDropShipper and assigns it to the DropShipper field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetDropShipper(v GetOrderCobCod200ResponseDataOrderDataInnerDropShipper) {
	o.DropShipper = &v
}

// GetTypeMeta returns the TypeMeta field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetTypeMeta() GetOrderCobCod200ResponseDataOrderDataInnerTypeMeta {
	if o == nil || IsNil(o.TypeMeta) {
		var ret GetOrderCobCod200ResponseDataOrderDataInnerTypeMeta
		return ret
	}
	return *o.TypeMeta
}

// GetTypeMetaOk returns a tuple with the TypeMeta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetTypeMetaOk() (*GetOrderCobCod200ResponseDataOrderDataInnerTypeMeta, bool) {
	if o == nil || IsNil(o.TypeMeta) {
		return nil, false
	}
	return o.TypeMeta, true
}

// HasTypeMeta returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasTypeMeta() bool {
	if o != nil && !IsNil(o.TypeMeta) {
		return true
	}

	return false
}

// SetTypeMeta gets a reference to the given GetOrderCobCod200ResponseDataOrderDataInnerTypeMeta and assigns it to the TypeMeta field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetTypeMeta(v GetOrderCobCod200ResponseDataOrderDataInnerTypeMeta) {
	o.TypeMeta = &v
}

// GetOrderShipmentFulfillment returns the OrderShipmentFulfillment field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderShipmentFulfillment() GetOrderCobCod200ResponseDataOrderDataInnerOrderShipmentFulfillment {
	if o == nil || IsNil(o.OrderShipmentFulfillment) {
		var ret GetOrderCobCod200ResponseDataOrderDataInnerOrderShipmentFulfillment
		return ret
	}
	return *o.OrderShipmentFulfillment
}

// GetOrderShipmentFulfillmentOk returns a tuple with the OrderShipmentFulfillment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetOrderShipmentFulfillmentOk() (*GetOrderCobCod200ResponseDataOrderDataInnerOrderShipmentFulfillment, bool) {
	if o == nil || IsNil(o.OrderShipmentFulfillment) {
		return nil, false
	}
	return o.OrderShipmentFulfillment, true
}

// HasOrderShipmentFulfillment returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasOrderShipmentFulfillment() bool {
	if o != nil && !IsNil(o.OrderShipmentFulfillment) {
		return true
	}

	return false
}

// SetOrderShipmentFulfillment gets a reference to the given GetOrderCobCod200ResponseDataOrderDataInnerOrderShipmentFulfillment and assigns it to the OrderShipmentFulfillment field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetOrderShipmentFulfillment(v GetOrderCobCod200ResponseDataOrderDataInnerOrderShipmentFulfillment) {
	o.OrderShipmentFulfillment = &v
}

// GetBookingData returns the BookingData field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetBookingData() GetOrderCobCod200ResponseDataOrderDataInnerBookingData {
	if o == nil || IsNil(o.BookingData) {
		var ret GetOrderCobCod200ResponseDataOrderDataInnerBookingData
		return ret
	}
	return *o.BookingData
}

// GetBookingDataOk returns a tuple with the BookingData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) GetBookingDataOk() (*GetOrderCobCod200ResponseDataOrderDataInnerBookingData, bool) {
	if o == nil || IsNil(o.BookingData) {
		return nil, false
	}
	return o.BookingData, true
}

// HasBookingData returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) HasBookingData() bool {
	if o != nil && !IsNil(o.BookingData) {
		return true
	}

	return false
}

// SetBookingData gets a reference to the given GetOrderCobCod200ResponseDataOrderDataInnerBookingData and assigns it to the BookingData field.
func (o *GetOrderCobCod200ResponseDataOrderDataInner) SetBookingData(v GetOrderCobCod200ResponseDataOrderDataInnerBookingData) {
	o.BookingData = &v
}

func (o GetOrderCobCod200ResponseDataOrderDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderCobCod200ResponseDataOrderDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.OrderHistory) {
		toSerialize["order_history"] = o.OrderHistory
	}
	if !IsNil(o.OrderDetail) {
		toSerialize["order_detail"] = o.OrderDetail
	}
	if !IsNil(o.DropShipper) {
		toSerialize["drop_shipper"] = o.DropShipper
	}
	if !IsNil(o.TypeMeta) {
		toSerialize["type_meta"] = o.TypeMeta
	}
	if !IsNil(o.OrderShipmentFulfillment) {
		toSerialize["order_shipment_fulfillment"] = o.OrderShipmentFulfillment
	}
	if !IsNil(o.BookingData) {
		toSerialize["booking_data"] = o.BookingData
	}
	return toSerialize, nil
}

type NullableGetOrderCobCod200ResponseDataOrderDataInner struct {
	value *GetOrderCobCod200ResponseDataOrderDataInner
	isSet bool
}

func (v NullableGetOrderCobCod200ResponseDataOrderDataInner) Get() *GetOrderCobCod200ResponseDataOrderDataInner {
	return v.value
}

func (v *NullableGetOrderCobCod200ResponseDataOrderDataInner) Set(val *GetOrderCobCod200ResponseDataOrderDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderCobCod200ResponseDataOrderDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderCobCod200ResponseDataOrderDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderCobCod200ResponseDataOrderDataInner(val *GetOrderCobCod200ResponseDataOrderDataInner) *NullableGetOrderCobCod200ResponseDataOrderDataInner {
	return &NullableGetOrderCobCod200ResponseDataOrderDataInner{value: val, isSet: true}
}

func (v NullableGetOrderCobCod200ResponseDataOrderDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderCobCod200ResponseDataOrderDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


