/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetListMessageDefaultResponseDataInnerAttributesContactAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetListMessageDefaultResponseDataInnerAttributesContactAttributes{}

// GetListMessageDefaultResponseDataInnerAttributesContactAttributes struct for GetListMessageDefaultResponseDataInnerAttributesContactAttributes
type GetListMessageDefaultResponseDataInnerAttributesContactAttributes struct {
	// User Name
	Name *string `json:"Name,omitempty"`
	// User Tag
	Tag *string `json:"tag,omitempty"`
	// User thumbnail
	Thumbnail *string `json:"thumbnail,omitempty"`
}

// NewGetListMessageDefaultResponseDataInnerAttributesContactAttributes instantiates a new GetListMessageDefaultResponseDataInnerAttributesContactAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetListMessageDefaultResponseDataInnerAttributesContactAttributes() *GetListMessageDefaultResponseDataInnerAttributesContactAttributes {
	this := GetListMessageDefaultResponseDataInnerAttributesContactAttributes{}
	return &this
}

// NewGetListMessageDefaultResponseDataInnerAttributesContactAttributesWithDefaults instantiates a new GetListMessageDefaultResponseDataInnerAttributesContactAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetListMessageDefaultResponseDataInnerAttributesContactAttributesWithDefaults() *GetListMessageDefaultResponseDataInnerAttributesContactAttributes {
	this := GetListMessageDefaultResponseDataInnerAttributesContactAttributes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) SetName(v string) {
	o.Name = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) SetTag(v string) {
	o.Tag = &v
}

// GetThumbnail returns the Thumbnail field value if set, zero value otherwise.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) GetThumbnail() string {
	if o == nil || IsNil(o.Thumbnail) {
		var ret string
		return ret
	}
	return *o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) GetThumbnailOk() (*string, bool) {
	if o == nil || IsNil(o.Thumbnail) {
		return nil, false
	}
	return o.Thumbnail, true
}

// HasThumbnail returns a boolean if a field has been set.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) HasThumbnail() bool {
	if o != nil && !IsNil(o.Thumbnail) {
		return true
	}

	return false
}

// SetThumbnail gets a reference to the given string and assigns it to the Thumbnail field.
func (o *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) SetThumbnail(v string) {
	o.Thumbnail = &v
}

func (o GetListMessageDefaultResponseDataInnerAttributesContactAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetListMessageDefaultResponseDataInnerAttributesContactAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Thumbnail) {
		toSerialize["thumbnail"] = o.Thumbnail
	}
	return toSerialize, nil
}

type NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes struct {
	value *GetListMessageDefaultResponseDataInnerAttributesContactAttributes
	isSet bool
}

func (v NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes) Get() *GetListMessageDefaultResponseDataInnerAttributesContactAttributes {
	return v.value
}

func (v *NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes) Set(val *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes(val *GetListMessageDefaultResponseDataInnerAttributesContactAttributes) *NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes {
	return &NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes{value: val, isSet: true}
}

func (v NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetListMessageDefaultResponseDataInnerAttributesContactAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


