/*
Tokopedia

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the ProductCampaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductCampaign{}

// ProductCampaign struct for ProductCampaign
type ProductCampaign struct {
	// Campaign Start Date (if any)
	StartDate *string `json:"StartDate,omitempty"`
	// Campaign End Date (if any)
	EndDate *string `json:"EndDate,omitempty"`
}

// NewProductCampaign instantiates a new ProductCampaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductCampaign() *ProductCampaign {
	this := ProductCampaign{}
	return &this
}

// NewProductCampaignWithDefaults instantiates a new ProductCampaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductCampaignWithDefaults() *ProductCampaign {
	this := ProductCampaign{}
	return &this
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ProductCampaign) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCampaign) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ProductCampaign) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *ProductCampaign) SetStartDate(v string) {
	o.StartDate = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *ProductCampaign) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCampaign) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *ProductCampaign) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *ProductCampaign) SetEndDate(v string) {
	o.EndDate = &v
}

func (o ProductCampaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductCampaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StartDate) {
		toSerialize["StartDate"] = o.StartDate
	}
	if !IsNil(o.EndDate) {
		toSerialize["EndDate"] = o.EndDate
	}
	return toSerialize, nil
}

type NullableProductCampaign struct {
	value *ProductCampaign
	isSet bool
}

func (v NullableProductCampaign) Get() *ProductCampaign {
	return v.value
}

func (v *NullableProductCampaign) Set(val *ProductCampaign) {
	v.value = val
	v.isSet = true
}

func (v NullableProductCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableProductCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductCampaign(val *ProductCampaign) *NullableProductCampaign {
	return &NullableProductCampaign{value: val, isSet: true}
}

func (v NullableProductCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


