/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetSingleOrder200ResponseDataBuyerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSingleOrder200ResponseDataBuyerInfo{}

// GetSingleOrder200ResponseDataBuyerInfo struct for GetSingleOrder200ResponseDataBuyerInfo
type GetSingleOrder200ResponseDataBuyerInfo struct {
	// Buyer User Unique Identifier
	BuyerId *int64 `json:"buyer_id,omitempty"`
	// Buyer Fullname
	BuyerFullname *string `json:"buyer_fullname,omitempty"`
	// Buyer Email Address
	BuyerEmail *string `json:"buyer_email,omitempty"`
	// Buyer Phone Number
	BuyerPhone *string `json:"buyer_phone,omitempty"`
}

// NewGetSingleOrder200ResponseDataBuyerInfo instantiates a new GetSingleOrder200ResponseDataBuyerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSingleOrder200ResponseDataBuyerInfo() *GetSingleOrder200ResponseDataBuyerInfo {
	this := GetSingleOrder200ResponseDataBuyerInfo{}
	return &this
}

// NewGetSingleOrder200ResponseDataBuyerInfoWithDefaults instantiates a new GetSingleOrder200ResponseDataBuyerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSingleOrder200ResponseDataBuyerInfoWithDefaults() *GetSingleOrder200ResponseDataBuyerInfo {
	this := GetSingleOrder200ResponseDataBuyerInfo{}
	return &this
}

// GetBuyerId returns the BuyerId field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerId() int64 {
	if o == nil || IsNil(o.BuyerId) {
		var ret int64
		return ret
	}
	return *o.BuyerId
}

// GetBuyerIdOk returns a tuple with the BuyerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.BuyerId) {
		return nil, false
	}
	return o.BuyerId, true
}

// HasBuyerId returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) HasBuyerId() bool {
	if o != nil && !IsNil(o.BuyerId) {
		return true
	}

	return false
}

// SetBuyerId gets a reference to the given int64 and assigns it to the BuyerId field.
func (o *GetSingleOrder200ResponseDataBuyerInfo) SetBuyerId(v int64) {
	o.BuyerId = &v
}

// GetBuyerFullname returns the BuyerFullname field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerFullname() string {
	if o == nil || IsNil(o.BuyerFullname) {
		var ret string
		return ret
	}
	return *o.BuyerFullname
}

// GetBuyerFullnameOk returns a tuple with the BuyerFullname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerFullnameOk() (*string, bool) {
	if o == nil || IsNil(o.BuyerFullname) {
		return nil, false
	}
	return o.BuyerFullname, true
}

// HasBuyerFullname returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) HasBuyerFullname() bool {
	if o != nil && !IsNil(o.BuyerFullname) {
		return true
	}

	return false
}

// SetBuyerFullname gets a reference to the given string and assigns it to the BuyerFullname field.
func (o *GetSingleOrder200ResponseDataBuyerInfo) SetBuyerFullname(v string) {
	o.BuyerFullname = &v
}

// GetBuyerEmail returns the BuyerEmail field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerEmail() string {
	if o == nil || IsNil(o.BuyerEmail) {
		var ret string
		return ret
	}
	return *o.BuyerEmail
}

// GetBuyerEmailOk returns a tuple with the BuyerEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerEmailOk() (*string, bool) {
	if o == nil || IsNil(o.BuyerEmail) {
		return nil, false
	}
	return o.BuyerEmail, true
}

// HasBuyerEmail returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) HasBuyerEmail() bool {
	if o != nil && !IsNil(o.BuyerEmail) {
		return true
	}

	return false
}

// SetBuyerEmail gets a reference to the given string and assigns it to the BuyerEmail field.
func (o *GetSingleOrder200ResponseDataBuyerInfo) SetBuyerEmail(v string) {
	o.BuyerEmail = &v
}

// GetBuyerPhone returns the BuyerPhone field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerPhone() string {
	if o == nil || IsNil(o.BuyerPhone) {
		var ret string
		return ret
	}
	return *o.BuyerPhone
}

// GetBuyerPhoneOk returns a tuple with the BuyerPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) GetBuyerPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.BuyerPhone) {
		return nil, false
	}
	return o.BuyerPhone, true
}

// HasBuyerPhone returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataBuyerInfo) HasBuyerPhone() bool {
	if o != nil && !IsNil(o.BuyerPhone) {
		return true
	}

	return false
}

// SetBuyerPhone gets a reference to the given string and assigns it to the BuyerPhone field.
func (o *GetSingleOrder200ResponseDataBuyerInfo) SetBuyerPhone(v string) {
	o.BuyerPhone = &v
}

func (o GetSingleOrder200ResponseDataBuyerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSingleOrder200ResponseDataBuyerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuyerId) {
		toSerialize["buyer_id"] = o.BuyerId
	}
	if !IsNil(o.BuyerFullname) {
		toSerialize["buyer_fullname"] = o.BuyerFullname
	}
	if !IsNil(o.BuyerEmail) {
		toSerialize["buyer_email"] = o.BuyerEmail
	}
	if !IsNil(o.BuyerPhone) {
		toSerialize["buyer_phone"] = o.BuyerPhone
	}
	return toSerialize, nil
}

type NullableGetSingleOrder200ResponseDataBuyerInfo struct {
	value *GetSingleOrder200ResponseDataBuyerInfo
	isSet bool
}

func (v NullableGetSingleOrder200ResponseDataBuyerInfo) Get() *GetSingleOrder200ResponseDataBuyerInfo {
	return v.value
}

func (v *NullableGetSingleOrder200ResponseDataBuyerInfo) Set(val *GetSingleOrder200ResponseDataBuyerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSingleOrder200ResponseDataBuyerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSingleOrder200ResponseDataBuyerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSingleOrder200ResponseDataBuyerInfo(val *GetSingleOrder200ResponseDataBuyerInfo) *NullableGetSingleOrder200ResponseDataBuyerInfo {
	return &NullableGetSingleOrder200ResponseDataBuyerInfo{value: val, isSet: true}
}

func (v NullableGetSingleOrder200ResponseDataBuyerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSingleOrder200ResponseDataBuyerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


