/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetSingleOrder200ResponseDataOrderInfoDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSingleOrder200ResponseDataOrderInfoDestination{}

// GetSingleOrder200ResponseDataOrderInfoDestination struct for GetSingleOrder200ResponseDataOrderInfoDestination
type GetSingleOrder200ResponseDataOrderInfoDestination struct {
	// Receiver Name
	ReceiverName *string `json:"receiver_name,omitempty"`
	// Receiver Phone Number
	ReceiverPhone *string `json:"receiver_phone,omitempty"`
	// Receiver Address Street
	AddressStreet *string `json:"address_street,omitempty"`
	// Receiver Address Distric
	AddressDistrict *string `json:"address_district,omitempty"`
	// Receiver Address City
	AddressCity *string `json:"address_city,omitempty"`
	// Receiver Address Province
	AddressProvince *string `json:"address_province,omitempty"`
	// Receiver Address Postal Code
	AddressPostal *string `json:"address_postal,omitempty"`
	// Receiver Customer Address Identifier
	CustomerAddressId *int64 `json:"customer_address_id,omitempty"`
	// Receiver District Unique Identifier
	DistrictId *int64 `json:"district_id,omitempty"`
	// Receiver City Unique Identifier
	CityId *int64 `json:"city_id,omitempty"`
	// Receiver Province Unique Identifier
	ProvinceId *int64 `json:"province_id,omitempty"`
}

// NewGetSingleOrder200ResponseDataOrderInfoDestination instantiates a new GetSingleOrder200ResponseDataOrderInfoDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSingleOrder200ResponseDataOrderInfoDestination() *GetSingleOrder200ResponseDataOrderInfoDestination {
	this := GetSingleOrder200ResponseDataOrderInfoDestination{}
	return &this
}

// NewGetSingleOrder200ResponseDataOrderInfoDestinationWithDefaults instantiates a new GetSingleOrder200ResponseDataOrderInfoDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSingleOrder200ResponseDataOrderInfoDestinationWithDefaults() *GetSingleOrder200ResponseDataOrderInfoDestination {
	this := GetSingleOrder200ResponseDataOrderInfoDestination{}
	return &this
}

// GetReceiverName returns the ReceiverName field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetReceiverName() string {
	if o == nil || IsNil(o.ReceiverName) {
		var ret string
		return ret
	}
	return *o.ReceiverName
}

// GetReceiverNameOk returns a tuple with the ReceiverName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetReceiverNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiverName) {
		return nil, false
	}
	return o.ReceiverName, true
}

// HasReceiverName returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasReceiverName() bool {
	if o != nil && !IsNil(o.ReceiverName) {
		return true
	}

	return false
}

// SetReceiverName gets a reference to the given string and assigns it to the ReceiverName field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetReceiverName(v string) {
	o.ReceiverName = &v
}

// GetReceiverPhone returns the ReceiverPhone field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetReceiverPhone() string {
	if o == nil || IsNil(o.ReceiverPhone) {
		var ret string
		return ret
	}
	return *o.ReceiverPhone
}

// GetReceiverPhoneOk returns a tuple with the ReceiverPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetReceiverPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiverPhone) {
		return nil, false
	}
	return o.ReceiverPhone, true
}

// HasReceiverPhone returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasReceiverPhone() bool {
	if o != nil && !IsNil(o.ReceiverPhone) {
		return true
	}

	return false
}

// SetReceiverPhone gets a reference to the given string and assigns it to the ReceiverPhone field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetReceiverPhone(v string) {
	o.ReceiverPhone = &v
}

// GetAddressStreet returns the AddressStreet field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressStreet() string {
	if o == nil || IsNil(o.AddressStreet) {
		var ret string
		return ret
	}
	return *o.AddressStreet
}

// GetAddressStreetOk returns a tuple with the AddressStreet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressStreetOk() (*string, bool) {
	if o == nil || IsNil(o.AddressStreet) {
		return nil, false
	}
	return o.AddressStreet, true
}

// HasAddressStreet returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasAddressStreet() bool {
	if o != nil && !IsNil(o.AddressStreet) {
		return true
	}

	return false
}

// SetAddressStreet gets a reference to the given string and assigns it to the AddressStreet field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetAddressStreet(v string) {
	o.AddressStreet = &v
}

// GetAddressDistrict returns the AddressDistrict field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressDistrict() string {
	if o == nil || IsNil(o.AddressDistrict) {
		var ret string
		return ret
	}
	return *o.AddressDistrict
}

// GetAddressDistrictOk returns a tuple with the AddressDistrict field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressDistrictOk() (*string, bool) {
	if o == nil || IsNil(o.AddressDistrict) {
		return nil, false
	}
	return o.AddressDistrict, true
}

// HasAddressDistrict returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasAddressDistrict() bool {
	if o != nil && !IsNil(o.AddressDistrict) {
		return true
	}

	return false
}

// SetAddressDistrict gets a reference to the given string and assigns it to the AddressDistrict field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetAddressDistrict(v string) {
	o.AddressDistrict = &v
}

// GetAddressCity returns the AddressCity field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressCity() string {
	if o == nil || IsNil(o.AddressCity) {
		var ret string
		return ret
	}
	return *o.AddressCity
}

// GetAddressCityOk returns a tuple with the AddressCity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressCityOk() (*string, bool) {
	if o == nil || IsNil(o.AddressCity) {
		return nil, false
	}
	return o.AddressCity, true
}

// HasAddressCity returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasAddressCity() bool {
	if o != nil && !IsNil(o.AddressCity) {
		return true
	}

	return false
}

// SetAddressCity gets a reference to the given string and assigns it to the AddressCity field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetAddressCity(v string) {
	o.AddressCity = &v
}

// GetAddressProvince returns the AddressProvince field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressProvince() string {
	if o == nil || IsNil(o.AddressProvince) {
		var ret string
		return ret
	}
	return *o.AddressProvince
}

// GetAddressProvinceOk returns a tuple with the AddressProvince field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressProvinceOk() (*string, bool) {
	if o == nil || IsNil(o.AddressProvince) {
		return nil, false
	}
	return o.AddressProvince, true
}

// HasAddressProvince returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasAddressProvince() bool {
	if o != nil && !IsNil(o.AddressProvince) {
		return true
	}

	return false
}

// SetAddressProvince gets a reference to the given string and assigns it to the AddressProvince field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetAddressProvince(v string) {
	o.AddressProvince = &v
}

// GetAddressPostal returns the AddressPostal field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressPostal() string {
	if o == nil || IsNil(o.AddressPostal) {
		var ret string
		return ret
	}
	return *o.AddressPostal
}

// GetAddressPostalOk returns a tuple with the AddressPostal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetAddressPostalOk() (*string, bool) {
	if o == nil || IsNil(o.AddressPostal) {
		return nil, false
	}
	return o.AddressPostal, true
}

// HasAddressPostal returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasAddressPostal() bool {
	if o != nil && !IsNil(o.AddressPostal) {
		return true
	}

	return false
}

// SetAddressPostal gets a reference to the given string and assigns it to the AddressPostal field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetAddressPostal(v string) {
	o.AddressPostal = &v
}

// GetCustomerAddressId returns the CustomerAddressId field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetCustomerAddressId() int64 {
	if o == nil || IsNil(o.CustomerAddressId) {
		var ret int64
		return ret
	}
	return *o.CustomerAddressId
}

// GetCustomerAddressIdOk returns a tuple with the CustomerAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetCustomerAddressIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CustomerAddressId) {
		return nil, false
	}
	return o.CustomerAddressId, true
}

// HasCustomerAddressId returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasCustomerAddressId() bool {
	if o != nil && !IsNil(o.CustomerAddressId) {
		return true
	}

	return false
}

// SetCustomerAddressId gets a reference to the given int64 and assigns it to the CustomerAddressId field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetCustomerAddressId(v int64) {
	o.CustomerAddressId = &v
}

// GetDistrictId returns the DistrictId field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetDistrictId() int64 {
	if o == nil || IsNil(o.DistrictId) {
		var ret int64
		return ret
	}
	return *o.DistrictId
}

// GetDistrictIdOk returns a tuple with the DistrictId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetDistrictIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DistrictId) {
		return nil, false
	}
	return o.DistrictId, true
}

// HasDistrictId returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasDistrictId() bool {
	if o != nil && !IsNil(o.DistrictId) {
		return true
	}

	return false
}

// SetDistrictId gets a reference to the given int64 and assigns it to the DistrictId field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetDistrictId(v int64) {
	o.DistrictId = &v
}

// GetCityId returns the CityId field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetCityId() int64 {
	if o == nil || IsNil(o.CityId) {
		var ret int64
		return ret
	}
	return *o.CityId
}

// GetCityIdOk returns a tuple with the CityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetCityIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CityId) {
		return nil, false
	}
	return o.CityId, true
}

// HasCityId returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasCityId() bool {
	if o != nil && !IsNil(o.CityId) {
		return true
	}

	return false
}

// SetCityId gets a reference to the given int64 and assigns it to the CityId field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetCityId(v int64) {
	o.CityId = &v
}

// GetProvinceId returns the ProvinceId field value if set, zero value otherwise.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetProvinceId() int64 {
	if o == nil || IsNil(o.ProvinceId) {
		var ret int64
		return ret
	}
	return *o.ProvinceId
}

// GetProvinceIdOk returns a tuple with the ProvinceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) GetProvinceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProvinceId) {
		return nil, false
	}
	return o.ProvinceId, true
}

// HasProvinceId returns a boolean if a field has been set.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) HasProvinceId() bool {
	if o != nil && !IsNil(o.ProvinceId) {
		return true
	}

	return false
}

// SetProvinceId gets a reference to the given int64 and assigns it to the ProvinceId field.
func (o *GetSingleOrder200ResponseDataOrderInfoDestination) SetProvinceId(v int64) {
	o.ProvinceId = &v
}

func (o GetSingleOrder200ResponseDataOrderInfoDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSingleOrder200ResponseDataOrderInfoDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReceiverName) {
		toSerialize["receiver_name"] = o.ReceiverName
	}
	if !IsNil(o.ReceiverPhone) {
		toSerialize["receiver_phone"] = o.ReceiverPhone
	}
	if !IsNil(o.AddressStreet) {
		toSerialize["address_street"] = o.AddressStreet
	}
	if !IsNil(o.AddressDistrict) {
		toSerialize["address_district"] = o.AddressDistrict
	}
	if !IsNil(o.AddressCity) {
		toSerialize["address_city"] = o.AddressCity
	}
	if !IsNil(o.AddressProvince) {
		toSerialize["address_province"] = o.AddressProvince
	}
	if !IsNil(o.AddressPostal) {
		toSerialize["address_postal"] = o.AddressPostal
	}
	if !IsNil(o.CustomerAddressId) {
		toSerialize["customer_address_id"] = o.CustomerAddressId
	}
	if !IsNil(o.DistrictId) {
		toSerialize["district_id"] = o.DistrictId
	}
	if !IsNil(o.CityId) {
		toSerialize["city_id"] = o.CityId
	}
	if !IsNil(o.ProvinceId) {
		toSerialize["province_id"] = o.ProvinceId
	}
	return toSerialize, nil
}

type NullableGetSingleOrder200ResponseDataOrderInfoDestination struct {
	value *GetSingleOrder200ResponseDataOrderInfoDestination
	isSet bool
}

func (v NullableGetSingleOrder200ResponseDataOrderInfoDestination) Get() *GetSingleOrder200ResponseDataOrderInfoDestination {
	return v.value
}

func (v *NullableGetSingleOrder200ResponseDataOrderInfoDestination) Set(val *GetSingleOrder200ResponseDataOrderInfoDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSingleOrder200ResponseDataOrderInfoDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSingleOrder200ResponseDataOrderInfoDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSingleOrder200ResponseDataOrderInfoDestination(val *GetSingleOrder200ResponseDataOrderInfoDestination) *NullableGetSingleOrder200ResponseDataOrderInfoDestination {
	return &NullableGetSingleOrder200ResponseDataOrderInfoDestination{value: val, isSet: true}
}

func (v NullableGetSingleOrder200ResponseDataOrderInfoDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSingleOrder200ResponseDataOrderInfoDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


