/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetOrderWebhook200ResponseDataOneOf1Logistics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderWebhook200ResponseDataOneOf1Logistics{}

// GetOrderWebhook200ResponseDataOneOf1Logistics struct for GetOrderWebhook200ResponseDataOneOf1Logistics
type GetOrderWebhook200ResponseDataOneOf1Logistics struct {
	ShippingId *int64 `json:"shipping_id,omitempty"`
	DistrictId *int64 `json:"district_id,omitempty"`
	CityId *int64 `json:"city_id,omitempty"`
	ProvinceId *int64 `json:"province_id,omitempty"`
	Geo *string `json:"geo,omitempty"`
	ShippingAgency *string `json:"shipping_agency,omitempty"`
	ServiceType *string `json:"service_type,omitempty"`
}

// NewGetOrderWebhook200ResponseDataOneOf1Logistics instantiates a new GetOrderWebhook200ResponseDataOneOf1Logistics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderWebhook200ResponseDataOneOf1Logistics() *GetOrderWebhook200ResponseDataOneOf1Logistics {
	this := GetOrderWebhook200ResponseDataOneOf1Logistics{}
	return &this
}

// NewGetOrderWebhook200ResponseDataOneOf1LogisticsWithDefaults instantiates a new GetOrderWebhook200ResponseDataOneOf1Logistics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderWebhook200ResponseDataOneOf1LogisticsWithDefaults() *GetOrderWebhook200ResponseDataOneOf1Logistics {
	this := GetOrderWebhook200ResponseDataOneOf1Logistics{}
	return &this
}

// GetShippingId returns the ShippingId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetShippingId() int64 {
	if o == nil || IsNil(o.ShippingId) {
		var ret int64
		return ret
	}
	return *o.ShippingId
}

// GetShippingIdOk returns a tuple with the ShippingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetShippingIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ShippingId) {
		return nil, false
	}
	return o.ShippingId, true
}

// HasShippingId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasShippingId() bool {
	if o != nil && !IsNil(o.ShippingId) {
		return true
	}

	return false
}

// SetShippingId gets a reference to the given int64 and assigns it to the ShippingId field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetShippingId(v int64) {
	o.ShippingId = &v
}

// GetDistrictId returns the DistrictId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetDistrictId() int64 {
	if o == nil || IsNil(o.DistrictId) {
		var ret int64
		return ret
	}
	return *o.DistrictId
}

// GetDistrictIdOk returns a tuple with the DistrictId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetDistrictIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DistrictId) {
		return nil, false
	}
	return o.DistrictId, true
}

// HasDistrictId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasDistrictId() bool {
	if o != nil && !IsNil(o.DistrictId) {
		return true
	}

	return false
}

// SetDistrictId gets a reference to the given int64 and assigns it to the DistrictId field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetDistrictId(v int64) {
	o.DistrictId = &v
}

// GetCityId returns the CityId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetCityId() int64 {
	if o == nil || IsNil(o.CityId) {
		var ret int64
		return ret
	}
	return *o.CityId
}

// GetCityIdOk returns a tuple with the CityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetCityIdOk() (*int64, bool) {
	if o == nil || IsNil(o.CityId) {
		return nil, false
	}
	return o.CityId, true
}

// HasCityId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasCityId() bool {
	if o != nil && !IsNil(o.CityId) {
		return true
	}

	return false
}

// SetCityId gets a reference to the given int64 and assigns it to the CityId field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetCityId(v int64) {
	o.CityId = &v
}

// GetProvinceId returns the ProvinceId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetProvinceId() int64 {
	if o == nil || IsNil(o.ProvinceId) {
		var ret int64
		return ret
	}
	return *o.ProvinceId
}

// GetProvinceIdOk returns a tuple with the ProvinceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetProvinceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ProvinceId) {
		return nil, false
	}
	return o.ProvinceId, true
}

// HasProvinceId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasProvinceId() bool {
	if o != nil && !IsNil(o.ProvinceId) {
		return true
	}

	return false
}

// SetProvinceId gets a reference to the given int64 and assigns it to the ProvinceId field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetProvinceId(v int64) {
	o.ProvinceId = &v
}

// GetGeo returns the Geo field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetGeo() string {
	if o == nil || IsNil(o.Geo) {
		var ret string
		return ret
	}
	return *o.Geo
}

// GetGeoOk returns a tuple with the Geo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetGeoOk() (*string, bool) {
	if o == nil || IsNil(o.Geo) {
		return nil, false
	}
	return o.Geo, true
}

// HasGeo returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasGeo() bool {
	if o != nil && !IsNil(o.Geo) {
		return true
	}

	return false
}

// SetGeo gets a reference to the given string and assigns it to the Geo field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetGeo(v string) {
	o.Geo = &v
}

// GetShippingAgency returns the ShippingAgency field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetShippingAgency() string {
	if o == nil || IsNil(o.ShippingAgency) {
		var ret string
		return ret
	}
	return *o.ShippingAgency
}

// GetShippingAgencyOk returns a tuple with the ShippingAgency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetShippingAgencyOk() (*string, bool) {
	if o == nil || IsNil(o.ShippingAgency) {
		return nil, false
	}
	return o.ShippingAgency, true
}

// HasShippingAgency returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasShippingAgency() bool {
	if o != nil && !IsNil(o.ShippingAgency) {
		return true
	}

	return false
}

// SetShippingAgency gets a reference to the given string and assigns it to the ShippingAgency field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetShippingAgency(v string) {
	o.ShippingAgency = &v
}

// GetServiceType returns the ServiceType field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetServiceType() string {
	if o == nil || IsNil(o.ServiceType) {
		var ret string
		return ret
	}
	return *o.ServiceType
}

// GetServiceTypeOk returns a tuple with the ServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) GetServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceType) {
		return nil, false
	}
	return o.ServiceType, true
}

// HasServiceType returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) HasServiceType() bool {
	if o != nil && !IsNil(o.ServiceType) {
		return true
	}

	return false
}

// SetServiceType gets a reference to the given string and assigns it to the ServiceType field.
func (o *GetOrderWebhook200ResponseDataOneOf1Logistics) SetServiceType(v string) {
	o.ServiceType = &v
}

func (o GetOrderWebhook200ResponseDataOneOf1Logistics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderWebhook200ResponseDataOneOf1Logistics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ShippingId) {
		toSerialize["shipping_id"] = o.ShippingId
	}
	if !IsNil(o.DistrictId) {
		toSerialize["district_id"] = o.DistrictId
	}
	if !IsNil(o.CityId) {
		toSerialize["city_id"] = o.CityId
	}
	if !IsNil(o.ProvinceId) {
		toSerialize["province_id"] = o.ProvinceId
	}
	if !IsNil(o.Geo) {
		toSerialize["geo"] = o.Geo
	}
	if !IsNil(o.ShippingAgency) {
		toSerialize["shipping_agency"] = o.ShippingAgency
	}
	if !IsNil(o.ServiceType) {
		toSerialize["service_type"] = o.ServiceType
	}
	return toSerialize, nil
}

type NullableGetOrderWebhook200ResponseDataOneOf1Logistics struct {
	value *GetOrderWebhook200ResponseDataOneOf1Logistics
	isSet bool
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1Logistics) Get() *GetOrderWebhook200ResponseDataOneOf1Logistics {
	return v.value
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1Logistics) Set(val *GetOrderWebhook200ResponseDataOneOf1Logistics) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1Logistics) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1Logistics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderWebhook200ResponseDataOneOf1Logistics(val *GetOrderWebhook200ResponseDataOneOf1Logistics) *NullableGetOrderWebhook200ResponseDataOneOf1Logistics {
	return &NullableGetOrderWebhook200ResponseDataOneOf1Logistics{value: val, isSet: true}
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1Logistics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1Logistics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


