/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the SendReplyRequestOneOf1Payload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendReplyRequestOneOf1Payload{}

// SendReplyRequestOneOf1Payload struct for SendReplyRequestOneOf1Payload
type SendReplyRequestOneOf1Payload struct {
	Thumbnail string `json:"thumbnail"`
	Identifier string `json:"identifier"`
	Title string `json:"title"`
	Price string `json:"price"`
	Url string `json:"url"`
}

// NewSendReplyRequestOneOf1Payload instantiates a new SendReplyRequestOneOf1Payload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendReplyRequestOneOf1Payload(thumbnail string, identifier string, title string, price string, url string) *SendReplyRequestOneOf1Payload {
	this := SendReplyRequestOneOf1Payload{}
	this.Thumbnail = thumbnail
	this.Identifier = identifier
	this.Title = title
	this.Price = price
	this.Url = url
	return &this
}

// NewSendReplyRequestOneOf1PayloadWithDefaults instantiates a new SendReplyRequestOneOf1Payload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendReplyRequestOneOf1PayloadWithDefaults() *SendReplyRequestOneOf1Payload {
	this := SendReplyRequestOneOf1Payload{}
	return &this
}

// GetThumbnail returns the Thumbnail field value
func (o *SendReplyRequestOneOf1Payload) GetThumbnail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value
// and a boolean to check if the value has been set.
func (o *SendReplyRequestOneOf1Payload) GetThumbnailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thumbnail, true
}

// SetThumbnail sets field value
func (o *SendReplyRequestOneOf1Payload) SetThumbnail(v string) {
	o.Thumbnail = v
}

// GetIdentifier returns the Identifier field value
func (o *SendReplyRequestOneOf1Payload) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *SendReplyRequestOneOf1Payload) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *SendReplyRequestOneOf1Payload) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTitle returns the Title field value
func (o *SendReplyRequestOneOf1Payload) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *SendReplyRequestOneOf1Payload) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *SendReplyRequestOneOf1Payload) SetTitle(v string) {
	o.Title = v
}

// GetPrice returns the Price field value
func (o *SendReplyRequestOneOf1Payload) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *SendReplyRequestOneOf1Payload) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *SendReplyRequestOneOf1Payload) SetPrice(v string) {
	o.Price = v
}

// GetUrl returns the Url field value
func (o *SendReplyRequestOneOf1Payload) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SendReplyRequestOneOf1Payload) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SendReplyRequestOneOf1Payload) SetUrl(v string) {
	o.Url = v
}

func (o SendReplyRequestOneOf1Payload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendReplyRequestOneOf1Payload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["thumbnail"] = o.Thumbnail
	toSerialize["identifier"] = o.Identifier
	toSerialize["title"] = o.Title
	toSerialize["price"] = o.Price
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

type NullableSendReplyRequestOneOf1Payload struct {
	value *SendReplyRequestOneOf1Payload
	isSet bool
}

func (v NullableSendReplyRequestOneOf1Payload) Get() *SendReplyRequestOneOf1Payload {
	return v.value
}

func (v *NullableSendReplyRequestOneOf1Payload) Set(val *SendReplyRequestOneOf1Payload) {
	v.value = val
	v.isSet = true
}

func (v NullableSendReplyRequestOneOf1Payload) IsSet() bool {
	return v.isSet
}

func (v *NullableSendReplyRequestOneOf1Payload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendReplyRequestOneOf1Payload(val *SendReplyRequestOneOf1Payload) *NullableSendReplyRequestOneOf1Payload {
	return &NullableSendReplyRequestOneOf1Payload{value: val, isSet: true}
}

func (v NullableSendReplyRequestOneOf1Payload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendReplyRequestOneOf1Payload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


