/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetOrderWebhook200ResponseDataOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderWebhook200ResponseDataOneOf1{}

// GetOrderWebhook200ResponseDataOneOf1 struct for GetOrderWebhook200ResponseDataOneOf1
type GetOrderWebhook200ResponseDataOneOf1 struct {
	FsId *int64 `json:"fs_id,omitempty"`
	OrderId *int64 `json:"order_id,omitempty"`
	InvoiceRefNum *string `json:"invoice_ref_num,omitempty"`
	Products []GetOrderWebhook200ResponseDataOneOfProductDetailsInner `json:"products,omitempty"`
	Customer *GetOrderWebhook200ResponseDataOneOf1Customer `json:"customer,omitempty"`
	Recipient *GetOrderWebhook200ResponseDataOneOf1Recipient `json:"recipient,omitempty"`
	ShopId *int64 `json:"shop_id,omitempty"`
	WarehouseId *int64 `json:"warehouse_id,omitempty"`
	ShopName *string `json:"shop_name,omitempty"`
	PaymentId *int64 `json:"payment_id,omitempty"`
	PaymentDate *string `json:"payment_date,omitempty"`
	Logistics *GetOrderWebhook200ResponseDataOneOf1Logistics `json:"logistics,omitempty"`
	Amt *GetOrderWebhook200ResponseDataOneOf1Amt `json:"amt,omitempty"`
	DropshipperInfo *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo `json:"dropshipper_info,omitempty"`
	VoucherInfo *GetOrderWebhook200ResponseDataOneOf1VoucherInfo `json:"voucher_info,omitempty"`
	DeviceType *string `json:"device_type,omitempty"`
	CreateTime *string `json:"create_time,omitempty"`
	// Order status code: * 0 - Seller cancel order. * 3 - Order Reject Due Empty Stock. * 5 - Order Canceled by Fraud * 6 - Order Rejected (Auto Cancel Out of Stock) * 10 - Order rejected by seller. * 15 - Instant Cancel by Buyer. * 100 - Order Created. * 103 - Wait for payment confirmation from third party. * 220 - Payment verified, order ready to process. * 221 - Waiting for partner approval. * 400 - Seller accept order. * 450 - Waiting for pickup. * 500 - Order shipment. * 501 - Status changed to waiting resi have no input. * 520 - Invalid shipment reference number (AWB). * 530 - Requested by user to correct invalid entry of shipment reference number. * 540 - Delivered to Pickup Point. * 550 - Return to Seller. * 600 - Order delivered. * 601 - Buyer open a case to finish an order. * 690 - Fraud Review * 700 - Order finished. 
	OrderStatus *int64 `json:"order_status,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	AcceptPartial *bool `json:"accept_partial,omitempty"`
}

// NewGetOrderWebhook200ResponseDataOneOf1 instantiates a new GetOrderWebhook200ResponseDataOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderWebhook200ResponseDataOneOf1() *GetOrderWebhook200ResponseDataOneOf1 {
	this := GetOrderWebhook200ResponseDataOneOf1{}
	return &this
}

// NewGetOrderWebhook200ResponseDataOneOf1WithDefaults instantiates a new GetOrderWebhook200ResponseDataOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderWebhook200ResponseDataOneOf1WithDefaults() *GetOrderWebhook200ResponseDataOneOf1 {
	this := GetOrderWebhook200ResponseDataOneOf1{}
	return &this
}

// GetFsId returns the FsId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetFsId() int64 {
	if o == nil || IsNil(o.FsId) {
		var ret int64
		return ret
	}
	return *o.FsId
}

// GetFsIdOk returns a tuple with the FsId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetFsIdOk() (*int64, bool) {
	if o == nil || IsNil(o.FsId) {
		return nil, false
	}
	return o.FsId, true
}

// HasFsId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasFsId() bool {
	if o != nil && !IsNil(o.FsId) {
		return true
	}

	return false
}

// SetFsId gets a reference to the given int64 and assigns it to the FsId field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetFsId(v int64) {
	o.FsId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetOrderId() int64 {
	if o == nil || IsNil(o.OrderId) {
		var ret int64
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetOrderIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int64 and assigns it to the OrderId field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetOrderId(v int64) {
	o.OrderId = &v
}

// GetInvoiceRefNum returns the InvoiceRefNum field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetInvoiceRefNum() string {
	if o == nil || IsNil(o.InvoiceRefNum) {
		var ret string
		return ret
	}
	return *o.InvoiceRefNum
}

// GetInvoiceRefNumOk returns a tuple with the InvoiceRefNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetInvoiceRefNumOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceRefNum) {
		return nil, false
	}
	return o.InvoiceRefNum, true
}

// HasInvoiceRefNum returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasInvoiceRefNum() bool {
	if o != nil && !IsNil(o.InvoiceRefNum) {
		return true
	}

	return false
}

// SetInvoiceRefNum gets a reference to the given string and assigns it to the InvoiceRefNum field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetInvoiceRefNum(v string) {
	o.InvoiceRefNum = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetProducts() []GetOrderWebhook200ResponseDataOneOfProductDetailsInner {
	if o == nil || IsNil(o.Products) {
		var ret []GetOrderWebhook200ResponseDataOneOfProductDetailsInner
		return ret
	}
	return o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetProductsOk() ([]GetOrderWebhook200ResponseDataOneOfProductDetailsInner, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasProducts() bool {
	if o != nil && !IsNil(o.Products) {
		return true
	}

	return false
}

// SetProducts gets a reference to the given []GetOrderWebhook200ResponseDataOneOfProductDetailsInner and assigns it to the Products field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetProducts(v []GetOrderWebhook200ResponseDataOneOfProductDetailsInner) {
	o.Products = v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetCustomer() GetOrderWebhook200ResponseDataOneOf1Customer {
	if o == nil || IsNil(o.Customer) {
		var ret GetOrderWebhook200ResponseDataOneOf1Customer
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetCustomerOk() (*GetOrderWebhook200ResponseDataOneOf1Customer, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given GetOrderWebhook200ResponseDataOneOf1Customer and assigns it to the Customer field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetCustomer(v GetOrderWebhook200ResponseDataOneOf1Customer) {
	o.Customer = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetRecipient() GetOrderWebhook200ResponseDataOneOf1Recipient {
	if o == nil || IsNil(o.Recipient) {
		var ret GetOrderWebhook200ResponseDataOneOf1Recipient
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetRecipientOk() (*GetOrderWebhook200ResponseDataOneOf1Recipient, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given GetOrderWebhook200ResponseDataOneOf1Recipient and assigns it to the Recipient field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetRecipient(v GetOrderWebhook200ResponseDataOneOf1Recipient) {
	o.Recipient = &v
}

// GetShopId returns the ShopId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetShopId() int64 {
	if o == nil || IsNil(o.ShopId) {
		var ret int64
		return ret
	}
	return *o.ShopId
}

// GetShopIdOk returns a tuple with the ShopId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetShopIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ShopId) {
		return nil, false
	}
	return o.ShopId, true
}

// HasShopId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasShopId() bool {
	if o != nil && !IsNil(o.ShopId) {
		return true
	}

	return false
}

// SetShopId gets a reference to the given int64 and assigns it to the ShopId field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetShopId(v int64) {
	o.ShopId = &v
}

// GetWarehouseId returns the WarehouseId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetWarehouseId() int64 {
	if o == nil || IsNil(o.WarehouseId) {
		var ret int64
		return ret
	}
	return *o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetWarehouseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.WarehouseId) {
		return nil, false
	}
	return o.WarehouseId, true
}

// HasWarehouseId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasWarehouseId() bool {
	if o != nil && !IsNil(o.WarehouseId) {
		return true
	}

	return false
}

// SetWarehouseId gets a reference to the given int64 and assigns it to the WarehouseId field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetWarehouseId(v int64) {
	o.WarehouseId = &v
}

// GetShopName returns the ShopName field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetShopName() string {
	if o == nil || IsNil(o.ShopName) {
		var ret string
		return ret
	}
	return *o.ShopName
}

// GetShopNameOk returns a tuple with the ShopName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetShopNameOk() (*string, bool) {
	if o == nil || IsNil(o.ShopName) {
		return nil, false
	}
	return o.ShopName, true
}

// HasShopName returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasShopName() bool {
	if o != nil && !IsNil(o.ShopName) {
		return true
	}

	return false
}

// SetShopName gets a reference to the given string and assigns it to the ShopName field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetShopName(v string) {
	o.ShopName = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetPaymentId() int64 {
	if o == nil || IsNil(o.PaymentId) {
		var ret int64
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetPaymentIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given int64 and assigns it to the PaymentId field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetPaymentId(v int64) {
	o.PaymentId = &v
}

// GetPaymentDate returns the PaymentDate field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetPaymentDate() string {
	if o == nil || IsNil(o.PaymentDate) {
		var ret string
		return ret
	}
	return *o.PaymentDate
}

// GetPaymentDateOk returns a tuple with the PaymentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetPaymentDateOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentDate) {
		return nil, false
	}
	return o.PaymentDate, true
}

// HasPaymentDate returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasPaymentDate() bool {
	if o != nil && !IsNil(o.PaymentDate) {
		return true
	}

	return false
}

// SetPaymentDate gets a reference to the given string and assigns it to the PaymentDate field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetPaymentDate(v string) {
	o.PaymentDate = &v
}

// GetLogistics returns the Logistics field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetLogistics() GetOrderWebhook200ResponseDataOneOf1Logistics {
	if o == nil || IsNil(o.Logistics) {
		var ret GetOrderWebhook200ResponseDataOneOf1Logistics
		return ret
	}
	return *o.Logistics
}

// GetLogisticsOk returns a tuple with the Logistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetLogisticsOk() (*GetOrderWebhook200ResponseDataOneOf1Logistics, bool) {
	if o == nil || IsNil(o.Logistics) {
		return nil, false
	}
	return o.Logistics, true
}

// HasLogistics returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasLogistics() bool {
	if o != nil && !IsNil(o.Logistics) {
		return true
	}

	return false
}

// SetLogistics gets a reference to the given GetOrderWebhook200ResponseDataOneOf1Logistics and assigns it to the Logistics field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetLogistics(v GetOrderWebhook200ResponseDataOneOf1Logistics) {
	o.Logistics = &v
}

// GetAmt returns the Amt field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetAmt() GetOrderWebhook200ResponseDataOneOf1Amt {
	if o == nil || IsNil(o.Amt) {
		var ret GetOrderWebhook200ResponseDataOneOf1Amt
		return ret
	}
	return *o.Amt
}

// GetAmtOk returns a tuple with the Amt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetAmtOk() (*GetOrderWebhook200ResponseDataOneOf1Amt, bool) {
	if o == nil || IsNil(o.Amt) {
		return nil, false
	}
	return o.Amt, true
}

// HasAmt returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasAmt() bool {
	if o != nil && !IsNil(o.Amt) {
		return true
	}

	return false
}

// SetAmt gets a reference to the given GetOrderWebhook200ResponseDataOneOf1Amt and assigns it to the Amt field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetAmt(v GetOrderWebhook200ResponseDataOneOf1Amt) {
	o.Amt = &v
}

// GetDropshipperInfo returns the DropshipperInfo field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetDropshipperInfo() GetOrderWebhook200ResponseDataOneOf1DropshipperInfo {
	if o == nil || IsNil(o.DropshipperInfo) {
		var ret GetOrderWebhook200ResponseDataOneOf1DropshipperInfo
		return ret
	}
	return *o.DropshipperInfo
}

// GetDropshipperInfoOk returns a tuple with the DropshipperInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetDropshipperInfoOk() (*GetOrderWebhook200ResponseDataOneOf1DropshipperInfo, bool) {
	if o == nil || IsNil(o.DropshipperInfo) {
		return nil, false
	}
	return o.DropshipperInfo, true
}

// HasDropshipperInfo returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasDropshipperInfo() bool {
	if o != nil && !IsNil(o.DropshipperInfo) {
		return true
	}

	return false
}

// SetDropshipperInfo gets a reference to the given GetOrderWebhook200ResponseDataOneOf1DropshipperInfo and assigns it to the DropshipperInfo field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetDropshipperInfo(v GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) {
	o.DropshipperInfo = &v
}

// GetVoucherInfo returns the VoucherInfo field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetVoucherInfo() GetOrderWebhook200ResponseDataOneOf1VoucherInfo {
	if o == nil || IsNil(o.VoucherInfo) {
		var ret GetOrderWebhook200ResponseDataOneOf1VoucherInfo
		return ret
	}
	return *o.VoucherInfo
}

// GetVoucherInfoOk returns a tuple with the VoucherInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetVoucherInfoOk() (*GetOrderWebhook200ResponseDataOneOf1VoucherInfo, bool) {
	if o == nil || IsNil(o.VoucherInfo) {
		return nil, false
	}
	return o.VoucherInfo, true
}

// HasVoucherInfo returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasVoucherInfo() bool {
	if o != nil && !IsNil(o.VoucherInfo) {
		return true
	}

	return false
}

// SetVoucherInfo gets a reference to the given GetOrderWebhook200ResponseDataOneOf1VoucherInfo and assigns it to the VoucherInfo field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetVoucherInfo(v GetOrderWebhook200ResponseDataOneOf1VoucherInfo) {
	o.VoucherInfo = &v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetDeviceType() string {
	if o == nil || IsNil(o.DeviceType) {
		var ret string
		return ret
	}
	return *o.DeviceType
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetDeviceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceType) {
		return nil, false
	}
	return o.DeviceType, true
}

// HasDeviceType returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasDeviceType() bool {
	if o != nil && !IsNil(o.DeviceType) {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given string and assigns it to the DeviceType field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetDeviceType(v string) {
	o.DeviceType = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetCreateTime() string {
	if o == nil || IsNil(o.CreateTime) {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetCreateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetOrderStatus returns the OrderStatus field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetOrderStatus() int64 {
	if o == nil || IsNil(o.OrderStatus) {
		var ret int64
		return ret
	}
	return *o.OrderStatus
}

// GetOrderStatusOk returns a tuple with the OrderStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetOrderStatusOk() (*int64, bool) {
	if o == nil || IsNil(o.OrderStatus) {
		return nil, false
	}
	return o.OrderStatus, true
}

// HasOrderStatus returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasOrderStatus() bool {
	if o != nil && !IsNil(o.OrderStatus) {
		return true
	}

	return false
}

// SetOrderStatus gets a reference to the given int64 and assigns it to the OrderStatus field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetOrderStatus(v int64) {
	o.OrderStatus = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetAcceptPartial returns the AcceptPartial field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetAcceptPartial() bool {
	if o == nil || IsNil(o.AcceptPartial) {
		var ret bool
		return ret
	}
	return *o.AcceptPartial
}

// GetAcceptPartialOk returns a tuple with the AcceptPartial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) GetAcceptPartialOk() (*bool, bool) {
	if o == nil || IsNil(o.AcceptPartial) {
		return nil, false
	}
	return o.AcceptPartial, true
}

// HasAcceptPartial returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1) HasAcceptPartial() bool {
	if o != nil && !IsNil(o.AcceptPartial) {
		return true
	}

	return false
}

// SetAcceptPartial gets a reference to the given bool and assigns it to the AcceptPartial field.
func (o *GetOrderWebhook200ResponseDataOneOf1) SetAcceptPartial(v bool) {
	o.AcceptPartial = &v
}

func (o GetOrderWebhook200ResponseDataOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderWebhook200ResponseDataOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FsId) {
		toSerialize["fs_id"] = o.FsId
	}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if !IsNil(o.InvoiceRefNum) {
		toSerialize["invoice_ref_num"] = o.InvoiceRefNum
	}
	if !IsNil(o.Products) {
		toSerialize["products"] = o.Products
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	if !IsNil(o.ShopId) {
		toSerialize["shop_id"] = o.ShopId
	}
	if !IsNil(o.WarehouseId) {
		toSerialize["warehouse_id"] = o.WarehouseId
	}
	if !IsNil(o.ShopName) {
		toSerialize["shop_name"] = o.ShopName
	}
	if !IsNil(o.PaymentId) {
		toSerialize["payment_id"] = o.PaymentId
	}
	if !IsNil(o.PaymentDate) {
		toSerialize["payment_date"] = o.PaymentDate
	}
	if !IsNil(o.Logistics) {
		toSerialize["logistics"] = o.Logistics
	}
	if !IsNil(o.Amt) {
		toSerialize["amt"] = o.Amt
	}
	if !IsNil(o.DropshipperInfo) {
		toSerialize["dropshipper_info"] = o.DropshipperInfo
	}
	if !IsNil(o.VoucherInfo) {
		toSerialize["voucher_info"] = o.VoucherInfo
	}
	if !IsNil(o.DeviceType) {
		toSerialize["device_type"] = o.DeviceType
	}
	if !IsNil(o.CreateTime) {
		toSerialize["create_time"] = o.CreateTime
	}
	if !IsNil(o.OrderStatus) {
		toSerialize["order_status"] = o.OrderStatus
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.AcceptPartial) {
		toSerialize["accept_partial"] = o.AcceptPartial
	}
	return toSerialize, nil
}

type NullableGetOrderWebhook200ResponseDataOneOf1 struct {
	value *GetOrderWebhook200ResponseDataOneOf1
	isSet bool
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1) Get() *GetOrderWebhook200ResponseDataOneOf1 {
	return v.value
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1) Set(val *GetOrderWebhook200ResponseDataOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderWebhook200ResponseDataOneOf1(val *GetOrderWebhook200ResponseDataOneOf1) *NullableGetOrderWebhook200ResponseDataOneOf1 {
	return &NullableGetOrderWebhook200ResponseDataOneOf1{value: val, isSet: true}
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


