/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the ViewCampaignProducts200ResponseDataProductsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewCampaignProducts200ResponseDataProductsInner{}

// ViewCampaignProducts200ResponseDataProductsInner struct for ViewCampaignProducts200ResponseDataProductsInner
type ViewCampaignProducts200ResponseDataProductsInner struct {
	// Product Unique Identifier
	ID *int64 `json:"ID,omitempty"`
	// Product Price
	Price *string `json:"price,omitempty"`
	Shop map[string]interface{} `json:"shop,omitempty"`
	// Product Maximum Order
	MaxOrder *int64 `json:"max_order,omitempty"`
	// Product Price Unformated
	PriceUnfmt *string `json:"price_unfmt,omitempty"`
	// Product Minimum Order
	MinOrder *int64 `json:"min_order,omitempty"`
	Campaign *ViewCampaignProducts200ResponseDataProductsInnerCampaign `json:"campaign,omitempty"`
}

// NewViewCampaignProducts200ResponseDataProductsInner instantiates a new ViewCampaignProducts200ResponseDataProductsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewCampaignProducts200ResponseDataProductsInner() *ViewCampaignProducts200ResponseDataProductsInner {
	this := ViewCampaignProducts200ResponseDataProductsInner{}
	return &this
}

// NewViewCampaignProducts200ResponseDataProductsInnerWithDefaults instantiates a new ViewCampaignProducts200ResponseDataProductsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewCampaignProducts200ResponseDataProductsInnerWithDefaults() *ViewCampaignProducts200ResponseDataProductsInner {
	this := ViewCampaignProducts200ResponseDataProductsInner{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetID() int64 {
	if o == nil || IsNil(o.ID) {
		var ret int64
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetIDOk() (*int64, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given int64 and assigns it to the ID field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetID(v int64) {
	o.ID = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetPrice() string {
	if o == nil || IsNil(o.Price) {
		var ret string
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetPriceOk() (*string, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given string and assigns it to the Price field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetPrice(v string) {
	o.Price = &v
}

// GetShop returns the Shop field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetShop() map[string]interface{} {
	if o == nil || IsNil(o.Shop) {
		var ret map[string]interface{}
		return ret
	}
	return o.Shop
}

// GetShopOk returns a tuple with the Shop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetShopOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Shop) {
		return map[string]interface{}{}, false
	}
	return o.Shop, true
}

// HasShop returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasShop() bool {
	if o != nil && !IsNil(o.Shop) {
		return true
	}

	return false
}

// SetShop gets a reference to the given map[string]interface{} and assigns it to the Shop field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetShop(v map[string]interface{}) {
	o.Shop = v
}

// GetMaxOrder returns the MaxOrder field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetMaxOrder() int64 {
	if o == nil || IsNil(o.MaxOrder) {
		var ret int64
		return ret
	}
	return *o.MaxOrder
}

// GetMaxOrderOk returns a tuple with the MaxOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetMaxOrderOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxOrder) {
		return nil, false
	}
	return o.MaxOrder, true
}

// HasMaxOrder returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasMaxOrder() bool {
	if o != nil && !IsNil(o.MaxOrder) {
		return true
	}

	return false
}

// SetMaxOrder gets a reference to the given int64 and assigns it to the MaxOrder field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetMaxOrder(v int64) {
	o.MaxOrder = &v
}

// GetPriceUnfmt returns the PriceUnfmt field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetPriceUnfmt() string {
	if o == nil || IsNil(o.PriceUnfmt) {
		var ret string
		return ret
	}
	return *o.PriceUnfmt
}

// GetPriceUnfmtOk returns a tuple with the PriceUnfmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetPriceUnfmtOk() (*string, bool) {
	if o == nil || IsNil(o.PriceUnfmt) {
		return nil, false
	}
	return o.PriceUnfmt, true
}

// HasPriceUnfmt returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasPriceUnfmt() bool {
	if o != nil && !IsNil(o.PriceUnfmt) {
		return true
	}

	return false
}

// SetPriceUnfmt gets a reference to the given string and assigns it to the PriceUnfmt field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetPriceUnfmt(v string) {
	o.PriceUnfmt = &v
}

// GetMinOrder returns the MinOrder field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetMinOrder() int64 {
	if o == nil || IsNil(o.MinOrder) {
		var ret int64
		return ret
	}
	return *o.MinOrder
}

// GetMinOrderOk returns a tuple with the MinOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetMinOrderOk() (*int64, bool) {
	if o == nil || IsNil(o.MinOrder) {
		return nil, false
	}
	return o.MinOrder, true
}

// HasMinOrder returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasMinOrder() bool {
	if o != nil && !IsNil(o.MinOrder) {
		return true
	}

	return false
}

// SetMinOrder gets a reference to the given int64 and assigns it to the MinOrder field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetMinOrder(v int64) {
	o.MinOrder = &v
}

// GetCampaign returns the Campaign field value if set, zero value otherwise.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetCampaign() ViewCampaignProducts200ResponseDataProductsInnerCampaign {
	if o == nil || IsNil(o.Campaign) {
		var ret ViewCampaignProducts200ResponseDataProductsInnerCampaign
		return ret
	}
	return *o.Campaign
}

// GetCampaignOk returns a tuple with the Campaign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) GetCampaignOk() (*ViewCampaignProducts200ResponseDataProductsInnerCampaign, bool) {
	if o == nil || IsNil(o.Campaign) {
		return nil, false
	}
	return o.Campaign, true
}

// HasCampaign returns a boolean if a field has been set.
func (o *ViewCampaignProducts200ResponseDataProductsInner) HasCampaign() bool {
	if o != nil && !IsNil(o.Campaign) {
		return true
	}

	return false
}

// SetCampaign gets a reference to the given ViewCampaignProducts200ResponseDataProductsInnerCampaign and assigns it to the Campaign field.
func (o *ViewCampaignProducts200ResponseDataProductsInner) SetCampaign(v ViewCampaignProducts200ResponseDataProductsInnerCampaign) {
	o.Campaign = &v
}

func (o ViewCampaignProducts200ResponseDataProductsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewCampaignProducts200ResponseDataProductsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Shop) {
		toSerialize["shop"] = o.Shop
	}
	if !IsNil(o.MaxOrder) {
		toSerialize["max_order"] = o.MaxOrder
	}
	if !IsNil(o.PriceUnfmt) {
		toSerialize["price_unfmt"] = o.PriceUnfmt
	}
	if !IsNil(o.MinOrder) {
		toSerialize["min_order"] = o.MinOrder
	}
	if !IsNil(o.Campaign) {
		toSerialize["campaign"] = o.Campaign
	}
	return toSerialize, nil
}

type NullableViewCampaignProducts200ResponseDataProductsInner struct {
	value *ViewCampaignProducts200ResponseDataProductsInner
	isSet bool
}

func (v NullableViewCampaignProducts200ResponseDataProductsInner) Get() *ViewCampaignProducts200ResponseDataProductsInner {
	return v.value
}

func (v *NullableViewCampaignProducts200ResponseDataProductsInner) Set(val *ViewCampaignProducts200ResponseDataProductsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViewCampaignProducts200ResponseDataProductsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViewCampaignProducts200ResponseDataProductsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewCampaignProducts200ResponseDataProductsInner(val *ViewCampaignProducts200ResponseDataProductsInner) *NullableViewCampaignProducts200ResponseDataProductsInner {
	return &NullableViewCampaignProducts200ResponseDataProductsInner{value: val, isSet: true}
}

func (v NullableViewCampaignProducts200ResponseDataProductsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewCampaignProducts200ResponseDataProductsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


