/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the EditProductV3200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditProductV3200Response{}

// EditProductV3200Response struct for EditProductV3200Response
type EditProductV3200Response struct {
	Header *ResponseHeader `json:"header,omitempty"`
	Data *EditProductV3200ResponseData `json:"data,omitempty"`
}

// NewEditProductV3200Response instantiates a new EditProductV3200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditProductV3200Response() *EditProductV3200Response {
	this := EditProductV3200Response{}
	return &this
}

// NewEditProductV3200ResponseWithDefaults instantiates a new EditProductV3200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditProductV3200ResponseWithDefaults() *EditProductV3200Response {
	this := EditProductV3200Response{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *EditProductV3200Response) GetHeader() ResponseHeader {
	if o == nil || IsNil(o.Header) {
		var ret ResponseHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProductV3200Response) GetHeaderOk() (*ResponseHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *EditProductV3200Response) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given ResponseHeader and assigns it to the Header field.
func (o *EditProductV3200Response) SetHeader(v ResponseHeader) {
	o.Header = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EditProductV3200Response) GetData() EditProductV3200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret EditProductV3200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProductV3200Response) GetDataOk() (*EditProductV3200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EditProductV3200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given EditProductV3200ResponseData and assigns it to the Data field.
func (o *EditProductV3200Response) SetData(v EditProductV3200ResponseData) {
	o.Data = &v
}

func (o EditProductV3200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditProductV3200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableEditProductV3200Response struct {
	value *EditProductV3200Response
	isSet bool
}

func (v NullableEditProductV3200Response) Get() *EditProductV3200Response {
	return v.value
}

func (v *NullableEditProductV3200Response) Set(val *EditProductV3200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableEditProductV3200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableEditProductV3200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditProductV3200Response(val *EditProductV3200Response) *NullableEditProductV3200Response {
	return &NullableEditProductV3200Response{value: val, isSet: true}
}

func (v NullableEditProductV3200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditProductV3200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


