/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the EditProductV3RequestProductsInnerVideosInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditProductV3RequestProductsInnerVideosInner{}

// EditProductV3RequestProductsInnerVideosInner struct for EditProductV3RequestProductsInnerVideosInner
type EditProductV3RequestProductsInnerVideosInner struct {
	Url *string `json:"url,omitempty"`
	Source *string `json:"source,omitempty"`
}

// NewEditProductV3RequestProductsInnerVideosInner instantiates a new EditProductV3RequestProductsInnerVideosInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditProductV3RequestProductsInnerVideosInner() *EditProductV3RequestProductsInnerVideosInner {
	this := EditProductV3RequestProductsInnerVideosInner{}
	return &this
}

// NewEditProductV3RequestProductsInnerVideosInnerWithDefaults instantiates a new EditProductV3RequestProductsInnerVideosInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditProductV3RequestProductsInnerVideosInnerWithDefaults() *EditProductV3RequestProductsInnerVideosInner {
	this := EditProductV3RequestProductsInnerVideosInner{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *EditProductV3RequestProductsInnerVideosInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProductV3RequestProductsInnerVideosInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *EditProductV3RequestProductsInnerVideosInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *EditProductV3RequestProductsInnerVideosInner) SetUrl(v string) {
	o.Url = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *EditProductV3RequestProductsInnerVideosInner) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProductV3RequestProductsInnerVideosInner) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *EditProductV3RequestProductsInnerVideosInner) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *EditProductV3RequestProductsInnerVideosInner) SetSource(v string) {
	o.Source = &v
}

func (o EditProductV3RequestProductsInnerVideosInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditProductV3RequestProductsInnerVideosInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableEditProductV3RequestProductsInnerVideosInner struct {
	value *EditProductV3RequestProductsInnerVideosInner
	isSet bool
}

func (v NullableEditProductV3RequestProductsInnerVideosInner) Get() *EditProductV3RequestProductsInnerVideosInner {
	return v.value
}

func (v *NullableEditProductV3RequestProductsInnerVideosInner) Set(val *EditProductV3RequestProductsInnerVideosInner) {
	v.value = val
	v.isSet = true
}

func (v NullableEditProductV3RequestProductsInnerVideosInner) IsSet() bool {
	return v.isSet
}

func (v *NullableEditProductV3RequestProductsInnerVideosInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditProductV3RequestProductsInnerVideosInner(val *EditProductV3RequestProductsInnerVideosInner) *NullableEditProductV3RequestProductsInnerVideosInner {
	return &NullableEditProductV3RequestProductsInnerVideosInner{value: val, isSet: true}
}

func (v NullableEditProductV3RequestProductsInnerVideosInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditProductV3RequestProductsInnerVideosInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


