/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the CreateProductV3DefaultResponseDataFailedRowsDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductV3DefaultResponseDataFailedRowsDataInner{}

// CreateProductV3DefaultResponseDataFailedRowsDataInner struct for CreateProductV3DefaultResponseDataFailedRowsDataInner
type CreateProductV3DefaultResponseDataFailedRowsDataInner struct {
	ProductName *string `json:"product_name,omitempty"`
	ProductPrice *float64 `json:"product_price,omitempty"`
	Sku *string `json:"sku,omitempty"`
	Error []string `json:"error,omitempty"`
}

// NewCreateProductV3DefaultResponseDataFailedRowsDataInner instantiates a new CreateProductV3DefaultResponseDataFailedRowsDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductV3DefaultResponseDataFailedRowsDataInner() *CreateProductV3DefaultResponseDataFailedRowsDataInner {
	this := CreateProductV3DefaultResponseDataFailedRowsDataInner{}
	return &this
}

// NewCreateProductV3DefaultResponseDataFailedRowsDataInnerWithDefaults instantiates a new CreateProductV3DefaultResponseDataFailedRowsDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductV3DefaultResponseDataFailedRowsDataInnerWithDefaults() *CreateProductV3DefaultResponseDataFailedRowsDataInner {
	this := CreateProductV3DefaultResponseDataFailedRowsDataInner{}
	return &this
}

// GetProductName returns the ProductName field value if set, zero value otherwise.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetProductName() string {
	if o == nil || IsNil(o.ProductName) {
		var ret string
		return ret
	}
	return *o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProductName) {
		return nil, false
	}
	return o.ProductName, true
}

// HasProductName returns a boolean if a field has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) HasProductName() bool {
	if o != nil && !IsNil(o.ProductName) {
		return true
	}

	return false
}

// SetProductName gets a reference to the given string and assigns it to the ProductName field.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) SetProductName(v string) {
	o.ProductName = &v
}

// GetProductPrice returns the ProductPrice field value if set, zero value otherwise.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetProductPrice() float64 {
	if o == nil || IsNil(o.ProductPrice) {
		var ret float64
		return ret
	}
	return *o.ProductPrice
}

// GetProductPriceOk returns a tuple with the ProductPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetProductPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.ProductPrice) {
		return nil, false
	}
	return o.ProductPrice, true
}

// HasProductPrice returns a boolean if a field has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) HasProductPrice() bool {
	if o != nil && !IsNil(o.ProductPrice) {
		return true
	}

	return false
}

// SetProductPrice gets a reference to the given float64 and assigns it to the ProductPrice field.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) SetProductPrice(v float64) {
	o.ProductPrice = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) SetSku(v string) {
	o.Sku = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetError() []string {
	if o == nil || IsNil(o.Error) {
		var ret []string
		return ret
	}
	return o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) GetErrorOk() ([]string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given []string and assigns it to the Error field.
func (o *CreateProductV3DefaultResponseDataFailedRowsDataInner) SetError(v []string) {
	o.Error = v
}

func (o CreateProductV3DefaultResponseDataFailedRowsDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductV3DefaultResponseDataFailedRowsDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductName) {
		toSerialize["product_name"] = o.ProductName
	}
	if !IsNil(o.ProductPrice) {
		toSerialize["product_price"] = o.ProductPrice
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableCreateProductV3DefaultResponseDataFailedRowsDataInner struct {
	value *CreateProductV3DefaultResponseDataFailedRowsDataInner
	isSet bool
}

func (v NullableCreateProductV3DefaultResponseDataFailedRowsDataInner) Get() *CreateProductV3DefaultResponseDataFailedRowsDataInner {
	return v.value
}

func (v *NullableCreateProductV3DefaultResponseDataFailedRowsDataInner) Set(val *CreateProductV3DefaultResponseDataFailedRowsDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductV3DefaultResponseDataFailedRowsDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductV3DefaultResponseDataFailedRowsDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductV3DefaultResponseDataFailedRowsDataInner(val *CreateProductV3DefaultResponseDataFailedRowsDataInner) *NullableCreateProductV3DefaultResponseDataFailedRowsDataInner {
	return &NullableCreateProductV3DefaultResponseDataFailedRowsDataInner{value: val, isSet: true}
}

func (v NullableCreateProductV3DefaultResponseDataFailedRowsDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductV3DefaultResponseDataFailedRowsDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


