/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetOrderWebhook200ResponseDataOneOf1DropshipperInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderWebhook200ResponseDataOneOf1DropshipperInfo{}

// GetOrderWebhook200ResponseDataOneOf1DropshipperInfo struct for GetOrderWebhook200ResponseDataOneOf1DropshipperInfo
type GetOrderWebhook200ResponseDataOneOf1DropshipperInfo struct {
	Name *string `json:"Name,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

// NewGetOrderWebhook200ResponseDataOneOf1DropshipperInfo instantiates a new GetOrderWebhook200ResponseDataOneOf1DropshipperInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderWebhook200ResponseDataOneOf1DropshipperInfo() *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo {
	this := GetOrderWebhook200ResponseDataOneOf1DropshipperInfo{}
	return &this
}

// NewGetOrderWebhook200ResponseDataOneOf1DropshipperInfoWithDefaults instantiates a new GetOrderWebhook200ResponseDataOneOf1DropshipperInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderWebhook200ResponseDataOneOf1DropshipperInfoWithDefaults() *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo {
	this := GetOrderWebhook200ResponseDataOneOf1DropshipperInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) SetName(v string) {
	o.Name = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) SetPhone(v string) {
	o.Phone = &v
}

func (o GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["Name"] = o.Name
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo struct {
	value *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo
	isSet bool
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo) Get() *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo {
	return v.value
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo) Set(val *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo(val *GetOrderWebhook200ResponseDataOneOf1DropshipperInfo) *NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo {
	return &NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo{value: val, isSet: true}
}

func (v NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderWebhook200ResponseDataOneOf1DropshipperInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


