/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the GetOrderCobCod200ResponseDataOrderDataInnerOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderCobCod200ResponseDataOrderDataInnerOrder{}

// GetOrderCobCod200ResponseDataOrderDataInnerOrder struct for GetOrderCobCod200ResponseDataOrderDataInnerOrder
type GetOrderCobCod200ResponseDataOrderDataInnerOrder struct {
	OrderId *int64 `json:"order_id,omitempty"`
	BuyerId *int64 `json:"buyer_id,omitempty"`
	SellerId *int64 `json:"seller_id,omitempty"`
	PaymentId *int64 `json:"payment_id,omitempty"`
	// Order status code: * 0 - Seller cancel order. * 3 - Order Reject Due Empty Stock. * 5 - Order Canceled by Fraud * 6 - Order Rejected (Auto Cancel Out of Stock) * 10 - Order rejected by seller. * 15 - Instant Cancel by Buyer. * 100 - Order Created. * 103 - Wait for payment confirmation from third party. * 220 - Payment verified, order ready to process. * 221 - Waiting for partner approval. * 400 - Seller accept order. * 450 - Waiting for pickup. * 500 - Order shipment. * 501 - Status changed to waiting resi have no input. * 520 - Invalid shipment reference number (AWB). * 530 - Requested by user to correct invalid entry of shipment reference number. * 540 - Delivered to Pickup Point. * 550 - Return to Seller. * 600 - Order delivered. * 601 - Buyer open a case to finish an order. * 690 - Fraud Review * 700 - Order finished. 
	OrderStatus *int64 `json:"order_status,omitempty"`
	InvoiceNumber *string `json:"invoice_number,omitempty"`
	InvoicePdfLink *string `json:"invoice_pdf_link,omitempty"`
	OpenAmt *int64 `json:"open_amt,omitempty"`
	PaymentAmtCod *int64 `json:"payment_amt_cod,omitempty"`
}

// NewGetOrderCobCod200ResponseDataOrderDataInnerOrder instantiates a new GetOrderCobCod200ResponseDataOrderDataInnerOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderCobCod200ResponseDataOrderDataInnerOrder() *GetOrderCobCod200ResponseDataOrderDataInnerOrder {
	this := GetOrderCobCod200ResponseDataOrderDataInnerOrder{}
	return &this
}

// NewGetOrderCobCod200ResponseDataOrderDataInnerOrderWithDefaults instantiates a new GetOrderCobCod200ResponseDataOrderDataInnerOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderCobCod200ResponseDataOrderDataInnerOrderWithDefaults() *GetOrderCobCod200ResponseDataOrderDataInnerOrder {
	this := GetOrderCobCod200ResponseDataOrderDataInnerOrder{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetOrderId() int64 {
	if o == nil || IsNil(o.OrderId) {
		var ret int64
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetOrderIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given int64 and assigns it to the OrderId field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetOrderId(v int64) {
	o.OrderId = &v
}

// GetBuyerId returns the BuyerId field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetBuyerId() int64 {
	if o == nil || IsNil(o.BuyerId) {
		var ret int64
		return ret
	}
	return *o.BuyerId
}

// GetBuyerIdOk returns a tuple with the BuyerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetBuyerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.BuyerId) {
		return nil, false
	}
	return o.BuyerId, true
}

// HasBuyerId returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasBuyerId() bool {
	if o != nil && !IsNil(o.BuyerId) {
		return true
	}

	return false
}

// SetBuyerId gets a reference to the given int64 and assigns it to the BuyerId field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetBuyerId(v int64) {
	o.BuyerId = &v
}

// GetSellerId returns the SellerId field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetSellerId() int64 {
	if o == nil || IsNil(o.SellerId) {
		var ret int64
		return ret
	}
	return *o.SellerId
}

// GetSellerIdOk returns a tuple with the SellerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetSellerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.SellerId) {
		return nil, false
	}
	return o.SellerId, true
}

// HasSellerId returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasSellerId() bool {
	if o != nil && !IsNil(o.SellerId) {
		return true
	}

	return false
}

// SetSellerId gets a reference to the given int64 and assigns it to the SellerId field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetSellerId(v int64) {
	o.SellerId = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetPaymentId() int64 {
	if o == nil || IsNil(o.PaymentId) {
		var ret int64
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetPaymentIdOk() (*int64, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given int64 and assigns it to the PaymentId field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetPaymentId(v int64) {
	o.PaymentId = &v
}

// GetOrderStatus returns the OrderStatus field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetOrderStatus() int64 {
	if o == nil || IsNil(o.OrderStatus) {
		var ret int64
		return ret
	}
	return *o.OrderStatus
}

// GetOrderStatusOk returns a tuple with the OrderStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetOrderStatusOk() (*int64, bool) {
	if o == nil || IsNil(o.OrderStatus) {
		return nil, false
	}
	return o.OrderStatus, true
}

// HasOrderStatus returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasOrderStatus() bool {
	if o != nil && !IsNil(o.OrderStatus) {
		return true
	}

	return false
}

// SetOrderStatus gets a reference to the given int64 and assigns it to the OrderStatus field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetOrderStatus(v int64) {
	o.OrderStatus = &v
}

// GetInvoiceNumber returns the InvoiceNumber field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetInvoiceNumber() string {
	if o == nil || IsNil(o.InvoiceNumber) {
		var ret string
		return ret
	}
	return *o.InvoiceNumber
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetInvoiceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceNumber) {
		return nil, false
	}
	return o.InvoiceNumber, true
}

// HasInvoiceNumber returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasInvoiceNumber() bool {
	if o != nil && !IsNil(o.InvoiceNumber) {
		return true
	}

	return false
}

// SetInvoiceNumber gets a reference to the given string and assigns it to the InvoiceNumber field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetInvoiceNumber(v string) {
	o.InvoiceNumber = &v
}

// GetInvoicePdfLink returns the InvoicePdfLink field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetInvoicePdfLink() string {
	if o == nil || IsNil(o.InvoicePdfLink) {
		var ret string
		return ret
	}
	return *o.InvoicePdfLink
}

// GetInvoicePdfLinkOk returns a tuple with the InvoicePdfLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetInvoicePdfLinkOk() (*string, bool) {
	if o == nil || IsNil(o.InvoicePdfLink) {
		return nil, false
	}
	return o.InvoicePdfLink, true
}

// HasInvoicePdfLink returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasInvoicePdfLink() bool {
	if o != nil && !IsNil(o.InvoicePdfLink) {
		return true
	}

	return false
}

// SetInvoicePdfLink gets a reference to the given string and assigns it to the InvoicePdfLink field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetInvoicePdfLink(v string) {
	o.InvoicePdfLink = &v
}

// GetOpenAmt returns the OpenAmt field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetOpenAmt() int64 {
	if o == nil || IsNil(o.OpenAmt) {
		var ret int64
		return ret
	}
	return *o.OpenAmt
}

// GetOpenAmtOk returns a tuple with the OpenAmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetOpenAmtOk() (*int64, bool) {
	if o == nil || IsNil(o.OpenAmt) {
		return nil, false
	}
	return o.OpenAmt, true
}

// HasOpenAmt returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasOpenAmt() bool {
	if o != nil && !IsNil(o.OpenAmt) {
		return true
	}

	return false
}

// SetOpenAmt gets a reference to the given int64 and assigns it to the OpenAmt field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetOpenAmt(v int64) {
	o.OpenAmt = &v
}

// GetPaymentAmtCod returns the PaymentAmtCod field value if set, zero value otherwise.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetPaymentAmtCod() int64 {
	if o == nil || IsNil(o.PaymentAmtCod) {
		var ret int64
		return ret
	}
	return *o.PaymentAmtCod
}

// GetPaymentAmtCodOk returns a tuple with the PaymentAmtCod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) GetPaymentAmtCodOk() (*int64, bool) {
	if o == nil || IsNil(o.PaymentAmtCod) {
		return nil, false
	}
	return o.PaymentAmtCod, true
}

// HasPaymentAmtCod returns a boolean if a field has been set.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) HasPaymentAmtCod() bool {
	if o != nil && !IsNil(o.PaymentAmtCod) {
		return true
	}

	return false
}

// SetPaymentAmtCod gets a reference to the given int64 and assigns it to the PaymentAmtCod field.
func (o *GetOrderCobCod200ResponseDataOrderDataInnerOrder) SetPaymentAmtCod(v int64) {
	o.PaymentAmtCod = &v
}

func (o GetOrderCobCod200ResponseDataOrderDataInnerOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderCobCod200ResponseDataOrderDataInnerOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if !IsNil(o.BuyerId) {
		toSerialize["buyer_id"] = o.BuyerId
	}
	if !IsNil(o.SellerId) {
		toSerialize["seller_id"] = o.SellerId
	}
	if !IsNil(o.PaymentId) {
		toSerialize["payment_id"] = o.PaymentId
	}
	if !IsNil(o.OrderStatus) {
		toSerialize["order_status"] = o.OrderStatus
	}
	if !IsNil(o.InvoiceNumber) {
		toSerialize["invoice_number"] = o.InvoiceNumber
	}
	if !IsNil(o.InvoicePdfLink) {
		toSerialize["invoice_pdf_link"] = o.InvoicePdfLink
	}
	if !IsNil(o.OpenAmt) {
		toSerialize["open_amt"] = o.OpenAmt
	}
	if !IsNil(o.PaymentAmtCod) {
		toSerialize["payment_amt_cod"] = o.PaymentAmtCod
	}
	return toSerialize, nil
}

type NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder struct {
	value *GetOrderCobCod200ResponseDataOrderDataInnerOrder
	isSet bool
}

func (v NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder) Get() *GetOrderCobCod200ResponseDataOrderDataInnerOrder {
	return v.value
}

func (v *NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder) Set(val *GetOrderCobCod200ResponseDataOrderDataInnerOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderCobCod200ResponseDataOrderDataInnerOrder(val *GetOrderCobCod200ResponseDataOrderDataInnerOrder) *NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder {
	return &NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder{value: val, isSet: true}
}

func (v NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderCobCod200ResponseDataOrderDataInnerOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


