/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the EditProductV2Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditProductV2Request{}

// EditProductV2Request struct for EditProductV2Request
type EditProductV2Request struct {
	Products []EditProductV2RequestProductsInner `json:"products"`
}

// NewEditProductV2Request instantiates a new EditProductV2Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditProductV2Request(products []EditProductV2RequestProductsInner) *EditProductV2Request {
	this := EditProductV2Request{}
	this.Products = products
	return &this
}

// NewEditProductV2RequestWithDefaults instantiates a new EditProductV2Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditProductV2RequestWithDefaults() *EditProductV2Request {
	this := EditProductV2Request{}
	return &this
}

// GetProducts returns the Products field value
func (o *EditProductV2Request) GetProducts() []EditProductV2RequestProductsInner {
	if o == nil {
		var ret []EditProductV2RequestProductsInner
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *EditProductV2Request) GetProductsOk() ([]EditProductV2RequestProductsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *EditProductV2Request) SetProducts(v []EditProductV2RequestProductsInner) {
	o.Products = v
}

func (o EditProductV2Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditProductV2Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["products"] = o.Products
	return toSerialize, nil
}

type NullableEditProductV2Request struct {
	value *EditProductV2Request
	isSet bool
}

func (v NullableEditProductV2Request) Get() *EditProductV2Request {
	return v.value
}

func (v *NullableEditProductV2Request) Set(val *EditProductV2Request) {
	v.value = val
	v.isSet = true
}

func (v NullableEditProductV2Request) IsSet() bool {
	return v.isSet
}

func (v *NullableEditProductV2Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditProductV2Request(val *EditProductV2Request) *NullableEditProductV2Request {
	return &NullableEditProductV2Request{value: val, isSet: true}
}

func (v NullableEditProductV2Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditProductV2Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


