/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the EditProductV2RequestProductsInnerVariant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditProductV2RequestProductsInnerVariant{}

// EditProductV2RequestProductsInnerVariant Variant of the product. The object keys includes: variant and product_variant. There are some field in variant entity that mandatory. For more detail please refer to this link
type EditProductV2RequestProductsInnerVariant struct {
	Products []EditProductV2RequestProductsInnerVariantProductsInner `json:"products"`
	Selection []EditProductV2RequestProductsInnerVariantSelectionInner `json:"selection,omitempty"`
	Sizecharts []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner `json:"sizecharts,omitempty"`
}

// NewEditProductV2RequestProductsInnerVariant instantiates a new EditProductV2RequestProductsInnerVariant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditProductV2RequestProductsInnerVariant(products []EditProductV2RequestProductsInnerVariantProductsInner) *EditProductV2RequestProductsInnerVariant {
	this := EditProductV2RequestProductsInnerVariant{}
	this.Products = products
	return &this
}

// NewEditProductV2RequestProductsInnerVariantWithDefaults instantiates a new EditProductV2RequestProductsInnerVariant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditProductV2RequestProductsInnerVariantWithDefaults() *EditProductV2RequestProductsInnerVariant {
	this := EditProductV2RequestProductsInnerVariant{}
	return &this
}

// GetProducts returns the Products field value
func (o *EditProductV2RequestProductsInnerVariant) GetProducts() []EditProductV2RequestProductsInnerVariantProductsInner {
	if o == nil {
		var ret []EditProductV2RequestProductsInnerVariantProductsInner
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *EditProductV2RequestProductsInnerVariant) GetProductsOk() ([]EditProductV2RequestProductsInnerVariantProductsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *EditProductV2RequestProductsInnerVariant) SetProducts(v []EditProductV2RequestProductsInnerVariantProductsInner) {
	o.Products = v
}

// GetSelection returns the Selection field value if set, zero value otherwise.
func (o *EditProductV2RequestProductsInnerVariant) GetSelection() []EditProductV2RequestProductsInnerVariantSelectionInner {
	if o == nil || IsNil(o.Selection) {
		var ret []EditProductV2RequestProductsInnerVariantSelectionInner
		return ret
	}
	return o.Selection
}

// GetSelectionOk returns a tuple with the Selection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProductV2RequestProductsInnerVariant) GetSelectionOk() ([]EditProductV2RequestProductsInnerVariantSelectionInner, bool) {
	if o == nil || IsNil(o.Selection) {
		return nil, false
	}
	return o.Selection, true
}

// HasSelection returns a boolean if a field has been set.
func (o *EditProductV2RequestProductsInnerVariant) HasSelection() bool {
	if o != nil && !IsNil(o.Selection) {
		return true
	}

	return false
}

// SetSelection gets a reference to the given []EditProductV2RequestProductsInnerVariantSelectionInner and assigns it to the Selection field.
func (o *EditProductV2RequestProductsInnerVariant) SetSelection(v []EditProductV2RequestProductsInnerVariantSelectionInner) {
	o.Selection = v
}

// GetSizecharts returns the Sizecharts field value if set, zero value otherwise.
func (o *EditProductV2RequestProductsInnerVariant) GetSizecharts() []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner {
	if o == nil || IsNil(o.Sizecharts) {
		var ret []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner
		return ret
	}
	return o.Sizecharts
}

// GetSizechartsOk returns a tuple with the Sizecharts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditProductV2RequestProductsInnerVariant) GetSizechartsOk() ([]EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner, bool) {
	if o == nil || IsNil(o.Sizecharts) {
		return nil, false
	}
	return o.Sizecharts, true
}

// HasSizecharts returns a boolean if a field has been set.
func (o *EditProductV2RequestProductsInnerVariant) HasSizecharts() bool {
	if o != nil && !IsNil(o.Sizecharts) {
		return true
	}

	return false
}

// SetSizecharts gets a reference to the given []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner and assigns it to the Sizecharts field.
func (o *EditProductV2RequestProductsInnerVariant) SetSizecharts(v []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner) {
	o.Sizecharts = v
}

func (o EditProductV2RequestProductsInnerVariant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditProductV2RequestProductsInnerVariant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["products"] = o.Products
	if !IsNil(o.Selection) {
		toSerialize["selection"] = o.Selection
	}
	if !IsNil(o.Sizecharts) {
		toSerialize["sizecharts"] = o.Sizecharts
	}
	return toSerialize, nil
}

type NullableEditProductV2RequestProductsInnerVariant struct {
	value *EditProductV2RequestProductsInnerVariant
	isSet bool
}

func (v NullableEditProductV2RequestProductsInnerVariant) Get() *EditProductV2RequestProductsInnerVariant {
	return v.value
}

func (v *NullableEditProductV2RequestProductsInnerVariant) Set(val *EditProductV2RequestProductsInnerVariant) {
	v.value = val
	v.isSet = true
}

func (v NullableEditProductV2RequestProductsInnerVariant) IsSet() bool {
	return v.isSet
}

func (v *NullableEditProductV2RequestProductsInnerVariant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditProductV2RequestProductsInnerVariant(val *EditProductV2RequestProductsInnerVariant) *NullableEditProductV2RequestProductsInnerVariant {
	return &NullableEditProductV2RequestProductsInnerVariant{value: val, isSet: true}
}

func (v NullableEditProductV2RequestProductsInnerVariant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditProductV2RequestProductsInnerVariant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


