/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the CreateProductV2RequestProductsInnerVariantInnerProductsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateProductV2RequestProductsInnerVariantInnerProductsInner{}

// CreateProductV2RequestProductsInnerVariantInnerProductsInner struct for CreateProductV2RequestProductsInnerVariantInnerProductsInner
type CreateProductV2RequestProductsInnerVariantInnerProductsInner struct {
	IsPrimary bool `json:"is_primary"`
	Status string `json:"status"`
	Price float64 `json:"price"`
	Stock int64 `json:"stock"`
	Sku string `json:"sku"`
	Combination []int64 `json:"combination"`
	Pictures []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner `json:"pictures"`
}

// NewCreateProductV2RequestProductsInnerVariantInnerProductsInner instantiates a new CreateProductV2RequestProductsInnerVariantInnerProductsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateProductV2RequestProductsInnerVariantInnerProductsInner(isPrimary bool, status string, price float64, stock int64, sku string, combination []int64, pictures []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner) *CreateProductV2RequestProductsInnerVariantInnerProductsInner {
	this := CreateProductV2RequestProductsInnerVariantInnerProductsInner{}
	this.IsPrimary = isPrimary
	this.Status = status
	this.Price = price
	this.Stock = stock
	this.Sku = sku
	this.Combination = combination
	this.Pictures = pictures
	return &this
}

// NewCreateProductV2RequestProductsInnerVariantInnerProductsInnerWithDefaults instantiates a new CreateProductV2RequestProductsInnerVariantInnerProductsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateProductV2RequestProductsInnerVariantInnerProductsInnerWithDefaults() *CreateProductV2RequestProductsInnerVariantInnerProductsInner {
	this := CreateProductV2RequestProductsInnerVariantInnerProductsInner{}
	var status string = "LIMITED"
	this.Status = status
	return &this
}

// GetIsPrimary returns the IsPrimary field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetIsPrimary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPrimary
}

// GetIsPrimaryOk returns a tuple with the IsPrimary field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetIsPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPrimary, true
}

// SetIsPrimary sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetIsPrimary(v bool) {
	o.IsPrimary = v
}

// GetStatus returns the Status field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetStatus(v string) {
	o.Status = v
}

// GetPrice returns the Price field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetPrice() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetPriceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetPrice(v float64) {
	o.Price = v
}

// GetStock returns the Stock field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetStock() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetStockOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetStock(v int64) {
	o.Stock = v
}

// GetSku returns the Sku field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetSku() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sku
}

// GetSkuOk returns a tuple with the Sku field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetSkuOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sku, true
}

// SetSku sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetSku(v string) {
	o.Sku = v
}

// GetCombination returns the Combination field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetCombination() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.Combination
}

// GetCombinationOk returns a tuple with the Combination field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetCombinationOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Combination, true
}

// SetCombination sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetCombination(v []int64) {
	o.Combination = v
}

// GetPictures returns the Pictures field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetPictures() []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner {
	if o == nil {
		var ret []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner
		return ret
	}

	return o.Pictures
}

// GetPicturesOk returns a tuple with the Pictures field value
// and a boolean to check if the value has been set.
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) GetPicturesOk() ([]EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pictures, true
}

// SetPictures sets field value
func (o *CreateProductV2RequestProductsInnerVariantInnerProductsInner) SetPictures(v []EditProductV2RequestProductsInnerVariantProductsInnerPicturesInner) {
	o.Pictures = v
}

func (o CreateProductV2RequestProductsInnerVariantInnerProductsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateProductV2RequestProductsInnerVariantInnerProductsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_primary"] = o.IsPrimary
	toSerialize["status"] = o.Status
	toSerialize["price"] = o.Price
	toSerialize["stock"] = o.Stock
	toSerialize["sku"] = o.Sku
	toSerialize["combination"] = o.Combination
	toSerialize["pictures"] = o.Pictures
	return toSerialize, nil
}

type NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner struct {
	value *CreateProductV2RequestProductsInnerVariantInnerProductsInner
	isSet bool
}

func (v NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner) Get() *CreateProductV2RequestProductsInnerVariantInnerProductsInner {
	return v.value
}

func (v *NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner) Set(val *CreateProductV2RequestProductsInnerVariantInnerProductsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateProductV2RequestProductsInnerVariantInnerProductsInner(val *CreateProductV2RequestProductsInnerVariantInnerProductsInner) *NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner {
	return &NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner{value: val, isSet: true}
}

func (v NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateProductV2RequestProductsInnerVariantInnerProductsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


