/*
Tokopedia API

Tokopedia API

API version: 1.0
Contact: dev@sirclo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tokopedia

import (
	"encoding/json"
)

// checks if the UpdateSlashPriceRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSlashPriceRequestInner{}

// UpdateSlashPriceRequestInner struct for UpdateSlashPriceRequestInner
type UpdateSlashPriceRequestInner struct {
	// Product unique identifier
	ProductId int64 `json:"product_id"`
	// Price that will be set into slash price campaign (please use either discounted_price or discount_percentage)
	DiscountedPrice *float64 `json:"discounted_price,omitempty"`
	// Total discount percentage that will be set into slash price campaign (please use either discounted_price or discount_percentage)
	DiscountPercentage *int64 `json:"discount_percentage,omitempty"`
	// Start time campaign in UNIX format(use GMT +7)
	StartTimeUnix int64 `json:"start_time_unix"`
	// End time campaign in UNIX format (use GMT +7)
	EndTimeUnix int64 `json:"end_time_unix"`
	// Maximum order per one transaction
	MaxOrder int64 `json:"max_order"`
	// body Flag to add slash price into specific warehouse
	IsCustomWarehouse *bool `json:"is_custom_warehouse,omitempty"`
	// Warehouse unique identifier
	WarehouseId *int64 `json:"warehouse_id,omitempty"`
	SlashPriceWarehouses *map[string]UpdateSlashPriceRequestInnerSlashPriceWarehousesValue `json:"slash_price_warehouses,omitempty"`
}

// NewUpdateSlashPriceRequestInner instantiates a new UpdateSlashPriceRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSlashPriceRequestInner(productId int64, startTimeUnix int64, endTimeUnix int64, maxOrder int64) *UpdateSlashPriceRequestInner {
	this := UpdateSlashPriceRequestInner{}
	this.ProductId = productId
	this.StartTimeUnix = startTimeUnix
	this.EndTimeUnix = endTimeUnix
	this.MaxOrder = maxOrder
	return &this
}

// NewUpdateSlashPriceRequestInnerWithDefaults instantiates a new UpdateSlashPriceRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSlashPriceRequestInnerWithDefaults() *UpdateSlashPriceRequestInner {
	this := UpdateSlashPriceRequestInner{}
	return &this
}

// GetProductId returns the ProductId field value
func (o *UpdateSlashPriceRequestInner) GetProductId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetProductIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *UpdateSlashPriceRequestInner) SetProductId(v int64) {
	o.ProductId = v
}

// GetDiscountedPrice returns the DiscountedPrice field value if set, zero value otherwise.
func (o *UpdateSlashPriceRequestInner) GetDiscountedPrice() float64 {
	if o == nil || IsNil(o.DiscountedPrice) {
		var ret float64
		return ret
	}
	return *o.DiscountedPrice
}

// GetDiscountedPriceOk returns a tuple with the DiscountedPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetDiscountedPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.DiscountedPrice) {
		return nil, false
	}
	return o.DiscountedPrice, true
}

// HasDiscountedPrice returns a boolean if a field has been set.
func (o *UpdateSlashPriceRequestInner) HasDiscountedPrice() bool {
	if o != nil && !IsNil(o.DiscountedPrice) {
		return true
	}

	return false
}

// SetDiscountedPrice gets a reference to the given float64 and assigns it to the DiscountedPrice field.
func (o *UpdateSlashPriceRequestInner) SetDiscountedPrice(v float64) {
	o.DiscountedPrice = &v
}

// GetDiscountPercentage returns the DiscountPercentage field value if set, zero value otherwise.
func (o *UpdateSlashPriceRequestInner) GetDiscountPercentage() int64 {
	if o == nil || IsNil(o.DiscountPercentage) {
		var ret int64
		return ret
	}
	return *o.DiscountPercentage
}

// GetDiscountPercentageOk returns a tuple with the DiscountPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetDiscountPercentageOk() (*int64, bool) {
	if o == nil || IsNil(o.DiscountPercentage) {
		return nil, false
	}
	return o.DiscountPercentage, true
}

// HasDiscountPercentage returns a boolean if a field has been set.
func (o *UpdateSlashPriceRequestInner) HasDiscountPercentage() bool {
	if o != nil && !IsNil(o.DiscountPercentage) {
		return true
	}

	return false
}

// SetDiscountPercentage gets a reference to the given int64 and assigns it to the DiscountPercentage field.
func (o *UpdateSlashPriceRequestInner) SetDiscountPercentage(v int64) {
	o.DiscountPercentage = &v
}

// GetStartTimeUnix returns the StartTimeUnix field value
func (o *UpdateSlashPriceRequestInner) GetStartTimeUnix() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartTimeUnix
}

// GetStartTimeUnixOk returns a tuple with the StartTimeUnix field value
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetStartTimeUnixOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTimeUnix, true
}

// SetStartTimeUnix sets field value
func (o *UpdateSlashPriceRequestInner) SetStartTimeUnix(v int64) {
	o.StartTimeUnix = v
}

// GetEndTimeUnix returns the EndTimeUnix field value
func (o *UpdateSlashPriceRequestInner) GetEndTimeUnix() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndTimeUnix
}

// GetEndTimeUnixOk returns a tuple with the EndTimeUnix field value
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetEndTimeUnixOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTimeUnix, true
}

// SetEndTimeUnix sets field value
func (o *UpdateSlashPriceRequestInner) SetEndTimeUnix(v int64) {
	o.EndTimeUnix = v
}

// GetMaxOrder returns the MaxOrder field value
func (o *UpdateSlashPriceRequestInner) GetMaxOrder() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxOrder
}

// GetMaxOrderOk returns a tuple with the MaxOrder field value
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetMaxOrderOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxOrder, true
}

// SetMaxOrder sets field value
func (o *UpdateSlashPriceRequestInner) SetMaxOrder(v int64) {
	o.MaxOrder = v
}

// GetIsCustomWarehouse returns the IsCustomWarehouse field value if set, zero value otherwise.
func (o *UpdateSlashPriceRequestInner) GetIsCustomWarehouse() bool {
	if o == nil || IsNil(o.IsCustomWarehouse) {
		var ret bool
		return ret
	}
	return *o.IsCustomWarehouse
}

// GetIsCustomWarehouseOk returns a tuple with the IsCustomWarehouse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetIsCustomWarehouseOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCustomWarehouse) {
		return nil, false
	}
	return o.IsCustomWarehouse, true
}

// HasIsCustomWarehouse returns a boolean if a field has been set.
func (o *UpdateSlashPriceRequestInner) HasIsCustomWarehouse() bool {
	if o != nil && !IsNil(o.IsCustomWarehouse) {
		return true
	}

	return false
}

// SetIsCustomWarehouse gets a reference to the given bool and assigns it to the IsCustomWarehouse field.
func (o *UpdateSlashPriceRequestInner) SetIsCustomWarehouse(v bool) {
	o.IsCustomWarehouse = &v
}

// GetWarehouseId returns the WarehouseId field value if set, zero value otherwise.
func (o *UpdateSlashPriceRequestInner) GetWarehouseId() int64 {
	if o == nil || IsNil(o.WarehouseId) {
		var ret int64
		return ret
	}
	return *o.WarehouseId
}

// GetWarehouseIdOk returns a tuple with the WarehouseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetWarehouseIdOk() (*int64, bool) {
	if o == nil || IsNil(o.WarehouseId) {
		return nil, false
	}
	return o.WarehouseId, true
}

// HasWarehouseId returns a boolean if a field has been set.
func (o *UpdateSlashPriceRequestInner) HasWarehouseId() bool {
	if o != nil && !IsNil(o.WarehouseId) {
		return true
	}

	return false
}

// SetWarehouseId gets a reference to the given int64 and assigns it to the WarehouseId field.
func (o *UpdateSlashPriceRequestInner) SetWarehouseId(v int64) {
	o.WarehouseId = &v
}

// GetSlashPriceWarehouses returns the SlashPriceWarehouses field value if set, zero value otherwise.
func (o *UpdateSlashPriceRequestInner) GetSlashPriceWarehouses() map[string]UpdateSlashPriceRequestInnerSlashPriceWarehousesValue {
	if o == nil || IsNil(o.SlashPriceWarehouses) {
		var ret map[string]UpdateSlashPriceRequestInnerSlashPriceWarehousesValue
		return ret
	}
	return *o.SlashPriceWarehouses
}

// GetSlashPriceWarehousesOk returns a tuple with the SlashPriceWarehouses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSlashPriceRequestInner) GetSlashPriceWarehousesOk() (*map[string]UpdateSlashPriceRequestInnerSlashPriceWarehousesValue, bool) {
	if o == nil || IsNil(o.SlashPriceWarehouses) {
		return nil, false
	}
	return o.SlashPriceWarehouses, true
}

// HasSlashPriceWarehouses returns a boolean if a field has been set.
func (o *UpdateSlashPriceRequestInner) HasSlashPriceWarehouses() bool {
	if o != nil && !IsNil(o.SlashPriceWarehouses) {
		return true
	}

	return false
}

// SetSlashPriceWarehouses gets a reference to the given map[string]UpdateSlashPriceRequestInnerSlashPriceWarehousesValue and assigns it to the SlashPriceWarehouses field.
func (o *UpdateSlashPriceRequestInner) SetSlashPriceWarehouses(v map[string]UpdateSlashPriceRequestInnerSlashPriceWarehousesValue) {
	o.SlashPriceWarehouses = &v
}

func (o UpdateSlashPriceRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSlashPriceRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["product_id"] = o.ProductId
	if !IsNil(o.DiscountedPrice) {
		toSerialize["discounted_price"] = o.DiscountedPrice
	}
	if !IsNil(o.DiscountPercentage) {
		toSerialize["discount_percentage"] = o.DiscountPercentage
	}
	toSerialize["start_time_unix"] = o.StartTimeUnix
	toSerialize["end_time_unix"] = o.EndTimeUnix
	toSerialize["max_order"] = o.MaxOrder
	if !IsNil(o.IsCustomWarehouse) {
		toSerialize["is_custom_warehouse"] = o.IsCustomWarehouse
	}
	if !IsNil(o.WarehouseId) {
		toSerialize["warehouse_id"] = o.WarehouseId
	}
	if !IsNil(o.SlashPriceWarehouses) {
		toSerialize["slash_price_warehouses"] = o.SlashPriceWarehouses
	}
	return toSerialize, nil
}

type NullableUpdateSlashPriceRequestInner struct {
	value *UpdateSlashPriceRequestInner
	isSet bool
}

func (v NullableUpdateSlashPriceRequestInner) Get() *UpdateSlashPriceRequestInner {
	return v.value
}

func (v *NullableUpdateSlashPriceRequestInner) Set(val *UpdateSlashPriceRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSlashPriceRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSlashPriceRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSlashPriceRequestInner(val *UpdateSlashPriceRequestInner) *NullableUpdateSlashPriceRequestInner {
	return &NullableUpdateSlashPriceRequestInner{value: val, isSet: true}
}

func (v NullableUpdateSlashPriceRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSlashPriceRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


