openapi: "3.0.2"
info:
  title: Zalora
  version: "1.0"
servers:
  - url: https://fs.tokopedia.net

paths:
  /test:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: OK
