/*
 * MP Connector API
 *
 * MP Connector API
 *
 * API version: v1.0.0
 * Contact: dev@sirclo.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package connector

type Variant struct {

	Sku string `json:"sku,omitempty"`

	VariantId string `json:"variant_id,omitempty"`
}
