openapi: 3.0.2
info:
  contact:
    email: dev@sirclo.com
    name: SIRCLO Tech
    url: https://sirclo.com
  title: Tokopedia Auth
  version: "1.0"
servers:
- url: https://accounts.tokopedia.com
security:
- basic: []
paths:
  /token:
    post:
      description: ""
      parameters:
      - explode: true
        in: query
        name: grant_type
        required: true
        schema:
          default: client_credentials
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
          description: OK
components:
  schemas:
    Token:
      example:
        access_token: LSPr7x7sRGaewzwZE6IcuA
        token_type: Bearer
        expires_in: 2592000
      properties:
        access_token:
          example: LSPr7x7sRGaewzwZE6IcuA
          type: string
        expires_in:
          example: 2592000
          format: int64
          type: integer
        token_type:
          example: Bearer
          type: string
      type: object
  securitySchemes:
    basic:
      scheme: basic
      type: http
