version: "3.9"
services:
  mock_tokopedia:
    image: stoplight/prism:4
    command: "mock -h 0.0.0.0 /tmp/api.oas3.yml"
    volumes:
      - ../oas/connector.yml:/tmp/api.oas3.yml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - "8080:4010"
